---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-secret
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: emqx
