---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.10",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
              "type": "dhcp",
              "provide": [
                {
                  "option": "host-name",
                  "fromArg": "dhcp-host-name"
                },
                {
                  "option": "host-name",
                  "fromArg": "K8S_POD_NAME"
                }
            ]
          }
        }
      ]
    }
