---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: security
stringData:
  token: 
    ENC[AES256_GCM,data:S4EQIo+t17uo481psNnHKrmuxFIpEwD5SpuhEaUY3hQLxOmAZKN74JGadP3VplDlZdY2oFLwTrKdnaNEgvBWatRBC4UWV8hmMLTS9C5RB7A+02pFmPKlOdY4XIDJP0Xl8hot2I+X46FHQM2zKtkMJ28OVzxrO7gIGEWl+eydw5aG0GgdCbBfNy9ZLD1I3m/3xAkqVkAjTz3N9Bu4nX5+YTVEZjzLMbvJuxPZ4EjMLh7KNEfOth6cpv6yd8shO2hacYiv+on1OZmNIRNvqOvY0cgqYcQiz+BsBQFKb5/3KVkGb8D4qm+Gf3hAKLFxVQFyHRJ9wYmbGB4/n30FoEe47uXXsIauNfMc9oBoMll9UVK6z57gEnKSNz4A3Oic/xZeZuUWujdRRV/GeiC+I+7USGEI4wg7KAhY6shNA0ChKa8a+maIA1Gz+4/68gYXwb9OHed/jXF1uRpyKyYRD6wxOcS2bdxXwqPEMmlZ1zWrhao4B2n022u3+K6HzxYyzXpEVrVZ0wumfOfW2LigIajLKtaas645jcoGrED/ukpD77JOBTWrKj9ydtcnPdRQJ/nXI8V2rgyvegk1Qkpr0xFLDheUJb7wau0phk49W1CjN3oHXKw0Feo/q77A8jqTBpeeRxInv+0zwc/oKUvsaQ1nT8jvdD8qWixuMMf381OZyFNQGJ5zctFY7iQTR21qFm//UCWqBZNzOm1HunkrpHPE9JLHKdIVTnvRvrexVF2sXzHkw3BLZ+qJsFmI6TCBK1LAQtm365tfgFfqJuJThysx2freFrB9qt+iIhDQPVS+QOmoAxNLvfI9NDhW2jAmVYzWoe9+mTWjv+M7vmxfJDYrTQeVMKrVgo3T1v/ODqIYVlWAmhuTcWS5NY+2El73T22Gy/sPAiZTaR9a0lGNcAPM83wCwRkHUprEbtI=,iv:lXW2IP1PGiaA3d7+Vwm7frCs4fJt8t1Z3XFjmr6Ltvo=,tag:hXZklHKnGubZJlC/1/esxQ==,type:str]
  1password-credentials.json: 
    ENC[AES256_GCM,data:0IUD3gn8CK7DV/6IGBKSqePRDGm09LPlcWWHLQJZupqertjJ7zrQ4XFG76g/FWhWRFHTIaqBcdsIjjmO680zPy4597APBHSxWIkB3aDQbv32FbvJtcGcBSYuEHQYJjdYNnntbOe1U01/4QJ6RDsE05J0V92tWHdksNXTrnCqRqFrsTEHyTXUvhh04jo4CRlNBtyftqrUsaxRmAD1MYcTAufIL6u6SKMmTS7iJtm03RTRk81MwVwvWDBbJ26o+VBtmZfhWwKNkEKIKW63HrobdlsGfMYBzZSdKgwnVOsp2myYzJjZ4mHY7hlfKsHF9tdu4FEZ4bFswZl23caL5E3Nw2FmYl1IlX/zUy8Q94+WyWz7y4J6QheZau0PDp6fQ+efTS7SGW0Fe3yXSEUgNu7Gq6HPZYnRh7+pH7cvj+Pscex+sgQV/Cy5UAIc4xYXi2Tv3W2L0fRSK1/gSBrNbPb+5d/KDpgOuOsUi0T0ld8gwfHYmY8RDuOc/FkqFmUcKiW8mDD9BK/qDAUeBge5Nd0DxMQaAzb6z7bApljsc3lYP2jwTJL/E2ECp63oiq0RB+YT85kLiauVzMuNlcxBQFbmrKgFckaJdIXsQ1VU3IUW3qn6JkwmSEJNsEexeQAuJEw7l6ZBogBTusmnT9Ad/gfn262BUzeDkgjHMnvNzHBv/kbA6ALey+rsqWiUvK0u8d2LqgYw46J1SWXhEka56vjMyuh9uJWnxHdCDWAOJ6VQMYkpnPD4mn7jiEDIW4KbTtH9rIAq/CCjX7LnZ6K/c2zBJ6y7xjr4mTE0t8GRWK57QR/lotV/jlciv4l0n/LPLPlWNP7vzR13FmV9ecbxPGqCAXn+Owste5/M4IQvjIkmNbjT8FR0xlOYDs1JOyoGCABM5+WN88l6uIlMkxd/ejQAfF9zIyflKAbCWH05RXolEKv+LTjyqcDymWjGUdMQbrm1DYCpUAoZBMvUj7/3FTaKuoyEhl5Iwma+3FlneYZf3f0k1bBa/879DgF8IPe1JVPodU+F/ibpdz6fZqNsBqFIqLFYmB8kVg5LKsPR2qwfC8e39lQNkvtUX/iyT+9UFcOvMfz9biJx3/Mt1REisjfepfa/9Gk0M+v1mC46mZLRbwX81mtCiP94TFtvb6kgmCs1dBHeoul0oJoxrU4fHPZa8PFcVzWJ3mJXmHuM3vlJhDm/+blP+likapTfxvAH/WvqXzxT3DRI4okY6XOEqGjta5uWljl1ZAijy7yCD+e2Tqc0ZP9Lxepev0cse4pLtXUnZZmAEYhCVXt6tsIQF0cKB7U13Dfu3Zkrqc56YvQ/XB9cIwiAtW6nc8FXzSsb1+0oLA+dSXGLBNyBbR+6piEKoWQZAulnko5uM+cF+OXJYzPmcPCf0euG+s7OelQoYV7qQgsRBcKiqyJzog5EX28jGwyzyV1t1qz9I4qyLmV77aY=,iv:qahDXUIR8Q34f+t8foAFCz20lqVPvpg1NDWx5yXF6mY=,tag:ivrFdiMjs3IXizZy0VSCKg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-09-03T21:35:37Z'
  mac: 
    ENC[AES256_GCM,data:X0Ehy2XnZWtjYtN/6OijX3L/XP1i1yoNwttezqKT09KsYMpNnh3FsOlXpZ27saWV23CFYz7v8nRaX+vMW+pwa4c8IQOMAi/8zUNTcVv3GzV2rgZ3rCU7n9D++tyOIHLg3JKJuyCRANk1vhibgQhgAbKPUsKcBDpsv0qYBqlDAnY=,iv:+tkK6CHjJT4IEWY2g3pbuZFwTbIMtTj8lu2qrsg8B9k=,tag:9JBSBCOwLrOaA5sGoVodeA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
