---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-internal-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-internal-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: adguard
        property: password
