---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-internal-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-internal-secrets
    creationPolicy: Owner
  data:
    - secretKey: pihole_api_key
      remoteRef:
        key: PiHole
        property: api-key
