---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: any-sync
  namespace: apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: any-sync-secret
    template:
      engineVersion: v2
      data:
        any-sync-consensusnode.yaml: |
          account:
              peerId: {{ .consensusnode_peerId }}
              peerKey: {{ .consensusnode_peerKey }}
              signingKey: {{ .consensusnode_signingKey }}
          drpc:
              stream:
                  maxMsgSizeMb: 256
          yamux:
              listenAddrs:
                  - 0.0.0.0:4530
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          quic:
              listenAddrs:
                  - 0.0.0.0:5530
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          network:
              id: {{ .network }}
              networkId: {{ .networkId }}
              nodes:
                  - peerId: {{ .coordinator_peerId }}
                    addresses:
                      - any-sync-coordinator:4830
                      - quic://any-sync-coordinator:5830
                      - any-sync.glants.xyz:4830
                      - quic://any-sync.glants.xyz:5830
                    types:
                      - coordinator
                  - peerId: {{ .consensusnode_peerId }}
                    addresses:
                      - any-sync-consensusnode:4530
                      - quic://any-sync-consensusnode:5530
                      - any-sync.glants.xyz:4530
                      - quic://any-sync.glants.xyz:5530
                    types:
                      - consensus
                  - peerId: {{ .node-1_peerId }}
                    addresses:
                      - any-sync-node-1:4430
                      - quic://any-sync-node-1:5430
                      - any-sync.glants.xyz:4430
                      - quic://any-sync.glants.xyz:5430
                    types:
                      - tree
                  - peerId: {{ .filenode_peerId}}
                    addresses:
                      - any-sync-filenode:4730
                      - quic://any-sync-filenode:5730
                      - any-sync.glants.xyz:4730
                      - quic://any-sync.glants.xyz:5730
                    types:
                      - file
          networkStorePath: /networkStore
          log:
              production: false
              defaultLevel: ""
              namedLevels: {}
          metric:
              addr: 0.0.0.0:8000
          mongo:
              connect: mongodb://any-sync-mongodb-0.any-sync-mongodb-headless:27017/?w=majority
              database: consensus
              logCollection: log
        any-sync-coordinator.yaml: |
          account:
              peerId: {{ .coordinator_peerId }}
              peerKey: {{ .coordinator_peerKey }}
              signingKey: {{ .coordinator_signingKey }}
          drpc:
              stream:
                  maxMsgSizeMb: 256
          yamux:
              listenAddrs:
                  - 0.0.0.0:4830
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          quic:
              listenAddrs:
                  - 0.0.0.0:5830
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          network:
              id: {{ .network }}
              networkId: {{ .networkId }}
              nodes:
                  - peerId: {{ .coordinator_peerId }}
                    addresses:
                      - any-sync-coordinator:4830
                      - quic://any-sync-coordinator:5830
                      - any-sync.glants.xyz:4830
                      - quic://any-sync.glants.xyz:5830
                    types:
                      - coordinator
                  - peerId: {{ .consensusnode_peerId }}
                    addresses:
                      - any-sync-consensusnode:4530
                      - quic://any-sync-consensusnode:5530
                      - any-sync.glants.xyz:4530
                      - quic://any-sync.glants.xyz:5530
                    types:
                      - consensus
                  - peerId: {{ .node-1_peerId }}
                    addresses:
                      - any-sync-node-1:4430
                      - quic://any-sync-node-1:5430
                      - any-sync.glants.xyz:4430
                      - quic://any-sync.glants.xyz:5430
                    types:
                      - tree
                  - peerId: {{ .filenode_peerId}}
                    addresses:
                      - any-sync-filenode:4730
                      - quic://any-sync-filenode:5730
                      - any-sync.glants.xyz:4730
                      - quic://any-sync.glants.xyz:5730
                    types:
                      - file
          networkStorePath: /networkStore
          log:
              production: false
              defaultLevel: ""
              namedLevels: {}
          metric:
              addr: 0.0.0.0:8000
          mongo:
              connect: any-sync-mongodb-0.any-sync-mongodb-headless:27017
              database: coordinator
              log: log
              spaces: spaces
          spaceStatus:
              runSeconds: 5
              deletionPeriodDays: 0
          defaultLimits:
              spaceMembersRead: 1000
              spaceMembersWrite: 1000
              sharedSpacesLimit: 1000
        any-sync-filenode.yaml: |
          account:
              peerId: {{ .filenode_peerId }}
              peerKey: {{ .filenode_peerKey }}
              signingKey: {{ .filenode_signingKey }}
          drpc:
              stream:
                  maxMsgSizeMb: 256
          yamux:
              listenAddrs:
                  - 0.0.0.0:4730
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          quic:
              listenAddrs:
                  - 0.0.0.0:5730
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          network:
              id: {{ .network }}
              networkId: {{ .networkId }}
              nodes:
                  - peerId: {{ .coordinator_peerId }}
                    addresses:
                      - any-sync-coordinator:4830
                      - quic://any-sync-coordinator:5830
                      - any-sync.glants.xyz:4830
                      - quic://any-sync.glants.xyz:5830
                    types:
                      - coordinator
                  - peerId: {{ .consensusnode_peerId }}
                    addresses:
                      - any-sync-consensusnode:4530
                      - quic://any-sync-consensusnode:5530
                      - any-sync.glants.xyz:4530
                      - quic://any-sync.glants.xyz:5530
                    types:
                      - consensus
                  - peerId: {{ .node-1_peerId }}
                    addresses:
                      - any-sync-node-1:4430
                      - quic://any-sync-node-1:5430
                      - any-sync.glants.xyz:4430
                      - quic://any-sync.glants.xyz:5430
                    types:
                      - tree
                  - peerId: {{ .filenode_peerId}}
                    addresses:
                      - any-sync-filenode:4730
                      - quic://any-sync-filenode:5730
                      - any-sync.glants.xyz:4730
                      - quic://any-sync.glants.xyz:5730
                    types:
                      - file
          networkStorePath: /networkStore
          log:
              production: false
              defaultLevel: ""
              namedLevels: {}
          metric:
              addr: 0.0.0.0:8000
          defaultLimit: 1099511627776
          s3Store:
              endpoint: https://nas.ur30.ru:30002
              bucket: any-sync
              indexBucket: any-sync
              region: us-east-1
              profile: default
              maxThreads: 16
              forcePathStyle: true
          redis:
              isCluster: false
              url: redis://any-sync-redis:6379?dial_timeout=3&read_timeout=6s
        any-sync-node-1.yaml: |
          account:
              peerId: {{ .node-1_peerId }}
              peerKey: {{ .node-1_peerKey }}
              signingKey: {{ .node-1_signingKey }}
          drpc:
              stream:
                  maxMsgSizeMb: 256
          yamux:
              listenAddrs:
                  - 0.0.0.0:4430
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          quic:
              listenAddrs:
                  - 0.0.0.0:5430
              writeTimeoutSec: 10
              dialTimeoutSec: 10
          network:
              id: {{ .network }}
              networkId: {{ .networkId }}
              nodes:
                  - peerId: {{ .coordinator_peerId }}
                    addresses:
                      - any-sync-coordinator:4830
                      - quic://any-sync-coordinator:5830
                      - any-sync.glants.xyz:4830
                      - quic://any-sync.glants.xyz:5830
                    types:
                      - coordinator
                  - peerId: {{ .consensusnode_peerId }}
                    addresses:
                      - any-sync-consensusnode:4530
                      - quic://any-sync-consensusnode:5530
                      - any-sync.glants.xyz:4530
                      - quic://any-sync.glants.xyz:5530
                    types:
                      - consensus
                  - peerId: {{ .node-1_peerId }}
                    addresses:
                      - any-sync-node-1:4430
                      - quic://any-sync-node-1:5430
                      - any-sync.glants.xyz:4430
                      - quic://any-sync.glants.xyz:5430
                    types:
                      - tree
                  - peerId: {{ .filenode_peerId}}
                    addresses:
                      - any-sync-filenode:4730
                      - quic://any-sync-filenode:5730
                      - any-sync.glants.xyz:4730
                      - quic://any-sync.glants.xyz:5730
                    types:
                      - file
          networkStorePath: /networkStore
          log:
              production: false
              defaultLevel: ""
              namedLevels: {}
          metric:
              addr: 0.0.0.0:8000
          space:
              gcTTL: 60
              syncPeriod: 600
          storage:
              path: /storage
          nodeSync:
              syncOnStart: true
              periodicSyncHours: 2
          apiServer:
              listenAddr: 0.0.0.0:8080

        network.yaml: |
          networkId: {{ .networkId }}
          nodes:
              - peerId: {{ .coordinator_peerId }}
                addresses:
                  - any-sync-coordinator:4830
                  - quic://any-sync-coordinator:5830
                  - any-sync.glants.xyz:4830
                  - quic://any-sync.glants.xyz:5830
                types:
                  - coordinator
              - peerId: {{ .consensusnode_peerId }}
                addresses:
                  - any-sync-consensusnode:4530
                  - quic://any-sync-consensusnode:5530
                  - any-sync.glants.xyz:4530
                  - quic://any-sync.glants.xyz:5530
                types:
                  - consensus
              - peerId: {{ .node-1_peerId }}
                addresses:
                  - any-sync-node-1:4430
                  - quic://any-sync-node-1:5430
                  - any-sync.glants.xyz:4430
                  - quic://any-sync.glants.xyz:5430
                types:
                  - tree
              - peerId: {{ .filenode_peerId}}
                addresses:
                  - any-sync-filenode:4730
                  - quic://any-sync-filenode:5730
                  - any-sync.glants.xyz:4730
                  - quic://any-sync.glants.xyz:5730
                types:
                  - file

        s3.conf: |
          [default]
          aws_access_key_id=any-sync
          aws_secret_access_key={{ .S3_SECRET_KEY }}
  dataFrom:
    - extract:
        key: any-sync
