---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: any-sync
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    # defaultPodOptions:
    #   securityContext:
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     runAsNonRoot: true
    #     fsGroup: 1000
    #     fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      consensusnode:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/anyproto/any-sync-consensusnode
              tag: v0.2.3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      coordinator:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/anyproto/any-sync-coordinator
              tag: v0.4.4
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      filenode:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/anyproto/any-sync-filenode
              tag: v0.8.7
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      node-1:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/anyproto/any-sync-node
              tag: v0.4.13
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
      redis:
        containers:
          redis:
            image:
              repository: redis/redis-stack-server
              tag: 7.2.0-v14
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
    service:
      consensusnode:
        controller: consensusnode
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.14
          io.cilium/lb-ipam-sharing-key: any-sync
          external-dns.alpha.kubernetes.io/hostname: any-sync.glants.xyz
          external-dns.alpha.kubernetes.io/type: internal
        ports:
          yamux:
            port: 4530
          quic:
            port: 5530
            protocol: UDP
      coordinator:
        controller: coordinator
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.14
          io.cilium/lb-ipam-sharing-key: any-sync
        ports:
          yamux:
            port: 4830
          quic:
            port: 5830
            protocol: UDP
      filenode:
        controller: filenode
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.14
          io.cilium/lb-ipam-sharing-key: any-sync
        ports:
          yamux:
            port: 4730
          quic:
            port: 5730
            protocol: UDP
      node-1:
        controller: node-1
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.14
          io.cilium/lb-ipam-sharing-key: any-sync
        ports:
          yamux:
            port: 4430
          quic:
            port: 5430
            protocol: UDP
      redis:
        controller: redis
        ports:
          http:
            port: 6379
    persistence:
      config:
        name: any-sync-secret
        type: secret
        advancedMounts:
          consensusnode:
            app:
              - path: /etc/any-sync-consensusnode/config.yml
                subPath: any-sync-consensusnode.yaml
          coordinator:
            app:
              - path: /etc/any-sync-coordinator/config.yml
                subPath: any-sync-coordinator.yaml
              - path: /etc/any-sync-coordinator/network.yml
                subPath: network.yaml
          filenode:
            app:
              - path: /etc/any-sync-filenode/config.yml
                subPath: any-sync-filenode.yaml
              - path: /root/.aws/credentials
                subPath: s3.conf
                readOnly: true
          node-1:
            app:
              - path: /etc/any-sync-node/config.yml
                subPath: any-sync-node-1.yaml
      data:
        existingClaim: any-sync-data-v1
        advancedMounts:
          node-1:
            app:
              - path: /storage
