---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: any-sync-data-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
