---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: extreme
  namespace: metallb-system
spec:
  holdTime: 1m30s
  keepaliveTime: 0s
  myASN: 65005
  peerASN: 65000
  peerAddress: 192.168.48.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: loadbalanced
  namespace: metallb-system
spec:
  addresses:
    - 192.168.40.0/21
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgpadvertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
    - loadbalanced
