---
apiVersion: v1
kind: Secret
metadata:
  name: kea-helm-values
  namespace: networking
type: Opaque
stringData:
  reservations.yaml: ENC[AES256_GCM,data:907ky+KEt7QmxlOuh1qmXgm0TtGkdWkCjVXY8jV9osaS9ztyhcX6pPuJlR75lgzD/XRC0Nf0dbc9usPhjJYxT4B0YaFAeSu/uRk2s6w6tfm8/kZWIdqI/sk8vRivkiYVECPyMxQQcH+QNxVRbjpn+arHFCIAO0rJwh0go+ukcL066l5/FUQMISEjk3KN5n37ieRUvcpq1Ob1SV/8iQ4oslzC0gR/es5wy9LE08Wbx0EqGkibfI5CJQF/dsKIOGXt+ykx1OYWNdm7N5bJSlL8C7njWngf+wrdcThx3bnvm0jpD/d0hDGcdCt13Mwlz3hKFv5V6vP1yef+/rNTKZUQOsEYK3Rx7xH90N6cyGXOPQTCIMYXqmXk8eUH5GH4wnsmY7FjOezE9yosjAnyQ/lj/s168JMlfW69lRIB8m14If8T/e2yrNnRd4CIdojQytIdBUZucuOdakvguNYsOaB9ERPnwYMzTczm0iiawS02s/PKCMLmCIehU5xD3SWg6y9h5RLKGgmu3j1FqkR6SUn+Wml9IKjBqfA3l898VaVrUnVSCLwlLVE4UlQLql09r3PYIyOIGmXV8KmuDfeIna3zH9tQhTFGuzoQwlC53vA9Dmmm622dVeGkXNLk4Zmb1NRv3pix7K+KowiBC/tuvXa7SiVidUJsAB+OVrn2NYvqw+NMsYJpXavTH9qVdVOAZd1bZL3fVLS0hyfsQeUzJmg0Y8Kr8xhHxp6xYVzCCGXvZXqcZX8K6t9O0/BKGCpaauTtzf6suti+gpbYO1uGhcy53lzoQDdx6ZcAIgiFj0q03OwRihEgCoMu/4i7hXOuVEa0HiSd4cACD7bw0V7kGRnkfewZq9nATvTYe5Tuhz+KerQ4FyOlYDDKcZSSu31wfW6DZHhxV41CuJXO1m3jbFUP2eytmVIUl0P5SYvSx0ymFfP5oRvlee+U6RkOWVAMSj5oy7UlMwTSVSzuGVj3LN0uMhJU4UD560YAGEA3Qu9HotBnp8EaEGTiVIeDL3dGaOKZWREVyx7PEYTQ2kHWJADDKafK/7NkajJkbKAZpOj2jExK+NFibY/u7OvcudUByT7rPjCFCT/bGeFufvtKyww2lYLtBffdbQLGedeVTv1aXocw5kU1bzOAyqmcWCQC0XchFfeVjBDoLkbm8UxCOjB5wovksVpSeE7ca2vShWq6xdmqbFjIgFsxgINxfY1FESjQqHz7KeOLvrEChV52PCrd7sLm2TxHSrYhUDbMkwWgYbErmaDK9yXvUsnVqfc0a7Z4YSR/UK3bS+MhLne7oiOxra3WXDNRGXxOMimLz7INMCoEMhpRklC4XoC2S/huhSuwKUvrT+Wzbd4wKnVYg4yHfSHSpg42F7E5hi/DlprtJviDBA04ZY0PV1CUcPVgFcZ5QBMNhsDkZhfn/Vu6wUySJ9zPJgFBZ0WZhbtXHZeQ4R1SMsvr3r4XNaPbtPVKPHjA8NXSin9zs11XIrdrzZficnE3egowsAfKxCu/W/mIfFieVrqwIgWM9NF7JfYgoR3VVMF0Nqh89EErUGC1gaSN29aV9H1GD2459v09PodHP6DrhZnGKxwWSMLKSPIQ7UGcxyoYfW8json7FQxr8ZXTuOO/6U4JA8Ay5XIEASkPCilXdVoVo4cZotPa+AaKsWpfJiT4OfYW42yF9rRF15PdM70j85mIkamhDAOdc9aDZpaTed83o5J1dO22eZu7NOU4rzoX5/VdbjSYrpbiynvcnZNgvG0hTB9n6ouTMgAWmA==,iv:t6U7GTuCtHQXf/YiUskIZtMVQAci+pVIhp7ZBe37dx4=,tag:dvK/jLqXY34wKO7/3lT55A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-10-23T23:44:18Z'
  mac: ENC[AES256_GCM,data:b1j0Nq82HwtLLA1S5pZQxMMhbB6x9Xm2hbzS2zQHj6HDe8A0Ml5x+zh4V9Rpj7oBEE3dbNgD0DHOnTUKPL3HIl/cBcYnXgqy80h4NzuJhhiSOikI3hiNlkzHmeYkbH/uM1SPfBmp2MeK8q2W4LTkvG593UF+bPu5Ulzrb8TMafk=,iv:MFCwkYZSMEfYq37RlgwFQNv9/hfGrDhJJ6YOvXQRHyU=,tag:4mhFdiAhoS5OC7m92/jYmA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
