---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://piraeus.io/helm-charts/
      chart: snapshot-controller
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/sig-storage/snapshot-controller
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v6.1.0
    replicaCount: 1
