---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless-redis
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/apps/paperless/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/apps/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-paperless-redis
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-democratic-csi-iscsi
