---
apiVersion: v1
kind: Service
metadata:
  name: external-archpeace
  namespace: monitoring
  labels:
    app: external-archpeace
spec:
  ports:
    - name: node-exporter
      port: 9100
  type: ExternalName
  externalName: 192.168.214.9
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-archpeace
  namespace: monitoring
  labels:
    app: external-archpeace
subsets:
  - addresses:
      - ip: 192.168.214.9
    ports:
      - name: node-exporter
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: archpeace
  namespace: monitoring
  labels:
    app: external-archpeace
    release: prometheus
    jobLabel: node-exporter
spec:
  selector:
    matchLabels:
      app: external-archpeace
  endpoints:
    - port: node-exporter
      interval: 60s
  jobLabel: jobLabel
