---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-external-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: Cloudflare
        property: external-dns
