---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://postfinance.github.io/kubelet-csr-approver
      chart: kubelet-csr-approver
      version: 1.2.11
      sourceRef:
        kind: HelmRepository
        name: postfinance-charts
        namespace: flux-system
      interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: kubelet-csr-approver-values
