---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: Flux
  channel: cluster
  secretRef:
    name: discord-webhook-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: OCIRepository
      name: '*'
    - kind: Terraform
      name: '*'
  exclusionList:
    - error.*lookup github\.com
    - error.*lookup raw\.githubusercontent\.com
    - dial.*tcp.*timeout
    - waiting.*socket
  suspend: false
