---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: loki
