---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-db-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: atuin
