---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ipmi-server
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    controllers:
      ipmi-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: sciapp/nojava-ipmi-kvm-server
              tag: v0.2.2
            env:
              KVM_CONFIG_PATH: &config /config/ipmi-server.yaml
              WEBAPP_PORT: &port 8080
              WEBAPP_BASE: http://ipmi-server.ur30.ru
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: ipmi-server
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: "external-nginx"
        hosts:
          - host: ipmi-server.ur30.ru
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: secret
        name: ipmi-server-secret
        globalMounts:
          - path: *config
            subPath: config.yaml
            readOnly: true
