---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate-secret
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_PASSWORD: '{{ .emqx_MQTT_PASSWORD }}'
        ENCRYPTION_KEY: '{{ .teslamate_ENCRYPTION_KEY }}'
        DATABASE_NAME: '{{ .teslamate_DATABASE_NAME }}'
        DATABASE_HOST: postgres-v15-rw.apps
        DATABASE_PASS: '{{ .teslamate_DATABASE_PASS }}'
        DATABASE_USER: '{{ .teslamate_DATABASE_USER }}'
        # Postgres Init
        POSTGRES_DB: '{{ .teslamate_DATABASE_NAME }}'
        POSTGRES_HOST: postgres-v15-rw.apps
        POSTGRES_SUPER_USER: '{{ .cloudnativepgsecret_USERNAME }}'
        POSTGRES_SUPER_PASS: '{{ .cloudnativepgsecret_PASSWORD}}'
        POSTGRES_PASS: '{{ .teslamate_DATABASE_PASS }}'
        POSTGRES_USER: '{{ .teslamate_DATABASE_USER }}'
  dataFrom:
    - extract:
        key: cloudnativepgsecret
      rewrite:
        - regexp:
            source: (.*)
            target: cloudnativepgsecret_$1
    - extract:
        key: teslamate
      rewrite:
        - regexp:
            source: (.*)
            target: teslamate_$1
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: (.*)
            target: emqx_$1
