---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: smarthome
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: teslamate/teslamate
      tag: 2.0.0
    env:
      TZ: Europe/Moscow
      DISABLE_MQTT: 'false'
      MQTT_HOST: emqx
      MQTT_USERNAME: mqtt
      DATABASE_HOST:
        valueFrom:
          secretKeyRef:
            name: smarthome-pgsql-pguser-teslamate
            key: host
      DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: smarthome-pgsql-pguser-teslamate
            key: dbname
      DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: smarthome-pgsql-pguser-teslamate
            key: user
      DATABASE_PASS:
        valueFrom:
          secretKeyRef:
            name: smarthome-pgsql-pguser-teslamate
            key: password
    envFrom:
      - secretRef:
          name: teslamate-secret
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.214.0/24, 10.13.12.0/24
        ingressClassName: internal-nginx
        hosts:
          - host: teslamate.home
            paths:
              - path: /
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
