---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zipline
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zipline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CORE_SECRET: '{{ .CORE_SECRET }}'
        DATASOURCE_S3_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        DATASOURCE_S3_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: zipline
