---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipline
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          main:
            image:
              repository: ghcr.io/diced/zipline
              tag: 3.7.11
            env:
              # Core config
              CORE_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: CORE_SECRET
              CORE_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: zipline-pgsql-pguser-zipline
                    key: uri
              CORE_RETURN_HTTPS: 'true'
              CORE_COMPRESSION_ENABLED: 'true'
              CORE_COMPRESSION_THRESHOLD: 200mb
              CORE_COMPRESSION_ON_DASHBOARD: 'true'
              # Datasources
              DATASOURCE_TYPE: s3
              DATASOURCE_S3_ACCESS_KEY_ID:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_ACCESS_KEY_ID
              DATASOURCE_S3_SECRET_ACCESS_KEY:
                valueFrom:
                  secretKeyRef:
                    name: zipline-secret
                    key: DATASOURCE_S3_SECRET_ACCESS_KEY
              DATASOURCE_S3_BUCKET: zipline
              DATASOURCE_S3_ENDPOINT: nas.ur30.ru
              DATASOURCE_S3_PORT: 30002
              DATASOURCE_S3_FORCE_S3_PATH: 'true'
              DATASOURCE_S3_USE_SSL: 'true'
              # Exif
              EXIF_REMOVE_GPS: 'true'
              # Features
              FEATURES_INVITES: 'false'
              FEATURES_ROBOTS_TXT: 'false'
              FEATURES_USER_REGISTRATION: 'false'
              # Uploader
              UPLOADER_DEFAULT_FORMAT: DATE
              UPLOADER_DISABLED_EXTENSIONS: ps1,pdf,bat,exe,sh,fish
              UPLOADER_FORMAT_DATE: YYYY-MM-DD_HH-mm-ss
              UPLOADER_DEFAULT_EXPIRATION: ''
              # URLs
              URLS_ROUTE: /go
              URLS_LENGTH: 6
              # Website
              WEBSITE_TITLE: zipline
              WEBSITE_SHOW_FILES_PER_USER: 'false'
              WEBSITE_SHOW_VERSION: 'false'
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: &url zipline.ur30.ru
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *url
            secretName: zipline-tls-secret
