---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: prom/snmp-exporter
      tag: v0.28.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 300Mi
      requests:
        memory: 50Mi
    configmapReload:
      name: configmap-reload
      image:
        repository: jimmidyson/configmap-reload
        tag: v0.9.0
        pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
      namespace: monitoring
      path: /snmp
      scrapeTimeout: 10s
      params:
        - module:
            - if_mib
          name: main-switch
          target: 172.16.5.254
