---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/prowlarr
      tag: 1.20.1
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Moscow
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          external-dns.alpha.kubernetes.io/type: internal
        ingressClassName: external-nginx
        hosts:
          - host: prowlarr.ur30.ru
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
      setGateway: 'true'
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
