---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/jackett
              tag: 0.21.2736
            env:
              TZ: Europe/Moscow
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /usr/bin/env
                      - bash
                      - -c
                      - curl --fail localhost:9117/health
                  failureThreshold: 5
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 250m
                memory: 64Mi
              limits:
                memory: 512Mi

        pod:
          annotations:
            setGateway: 'true'
          enableServiceLinks: false
          securityContext:
            fsGroup: 568

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 9117

    ingress:
      main:
        enabled: true
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          external-dns.alpha.kubernetes.io/type: internal
        hosts:
          - host: &host '{{ .Release.Name }}.ur30.ru'
            paths:
              - path: /
                service:
                  name: main
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: jackett-config-v1
        mountPath: /config
