---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: any-sync-mongodb
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: 16.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    architecture: replicaset
    replicaCount: 1
    auth:
      enabled: false
    arbiter:
      enabled: false
      pdb:
        minAvailable: 0
    pdb:
      minAvailable: 0
    persistence:
      enabled: true
      storageClass: freenas-iscsi-csi
      size: 8Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 400m
