---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: talos-backup-secret
  namespace: backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: talos-backup-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: talos-backup
