---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-secret
  namespace: backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rclone-secret
    creationPolicy: Owner
  data:
    - secretKey: rclone.conf
      remoteRef:
        key: rclone
        property: rclone.conf
