---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: paperless
        property: ADMIN_USERNAME
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: paperless
        property: ADMIN_PASSWORD
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: paperless
        property: SECRET_KEY
