---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
  namespace: apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        VIKUNJA_AUTH_OPENID_PROVIDERS_SSO_CLIENTSECRET: '{{ .CLIENT_SECRET }}'
  dataFrom:
    - extract:
        key: vikunja
