---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mikrotik-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          devices:
          - name: mikrotik
            address: 172.16.30.1
            username: {{ .mikrotik_USERNAME }}
            password: {{ .mikrotik_PASSWORD }}
          features:
            health: true
            netwatch: true
            monitor: true

  dataFrom:
    - extract:
        key: *name
      rewrite:
        - regexp:
            source: (.*)
            target: mikrotik_$1
