---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-exporter
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mikrotik-exporter
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: mikrotik-exporter
      labels:
        app.kubernetes.io/name: mikrotik-exporter
    spec:
      volumes:
        - name: mikrotik-exporter
          secret:
            secretName: mikrotik-exporter
            optional: false
      containers:
        - name: mikrotik-exporter
          image: nshttpd/mikrotik-exporter:1.0.11
          args: [-config-file /tmp/config.yaml]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/config.yaml
              subPath: config.yaml
              name: mikrotik-exporter
          ports:
            - name: prometheus
              containerPort: 9436
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mikrotik-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mikrotik-exporter
  ports:
    - name: prometheus
      port: 9436
      protocol: TCP
      targetPort: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mikrotik-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mikrotik-exporter
  endpoints:
    - port: prometheus
