---
apiVersion: v1
kind: Secret
metadata:
  name: mikrotik-exporter
  namespace: monitoring
stringData:
  config.yaml: ENC[AES256_GCM,data:az8kAGr624+9LFifhUd9/vGPxRNh9HaDkIJ6qj1L8GBhl+StweteeTZtSGQFCKrH2+0gIJSshewbJFd0X/igHuvhL2hypCG/FOUM6Iu+uE60JVbZUvo1FxN4pR+mSyjvlwPYGRS6vDG9HqQgIYMIIItLUFwPSN2oR1Rdp0a7+fKAvi4gu0T1o8jMUc6xuvVG6Fw32ip7G6+f3tvy8xf26uJmC0b6uIA=,iv:D0w29u/QpDHttZ4i9nCcGKpwIPc5JsW4jTlrC3KWVCs=,tag:leQ/WQ2dVToTiMf+xFNT5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-08-01T20:31:08Z'
  mac: ENC[AES256_GCM,data:pjKMpCSOxQ+9hO1lLtIXrrNGIk+p1CjkpI1VgRMTcXTD5hSVC4K2AL52BIbZ2ccHn/2taCAu74ECaFx//d/b9h7bWwhHH5lclgxlabMIR1MSvmIH7Sy+sHluijVfAzcnG7A8GlYERenEZpkEat+dnUICbmXgpGMqQ7945ZLupC8=,iv:jCTN083N3K7n3cOoNLiGW9RPgq6ew5Qt1yPooDqPZKk=,tag:Br3ftVsDrqeZiP9VOjF/pw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
