---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://charts.jetstack.io chart=cert-manager type=helm
  - https://github.com/jetstack/cert-manager/releases/download/v1.17.1/cert-manager.crds.yaml
commonAnnotations:
  meta.helm.sh/release-name: cert-manager
  meta.helm.sh/release-namespace: cert-manager
commonLabels:
  app.kubernetes.io/managed-by: Helm
