---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-public-pv
  namespace: vpn
spec:
  storageClassName: public-vpn
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: /mnt/Storinator/Public
  mountOptions:
    - noatime
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-public-pvc
  namespace: vpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: public-vpn
  resources:
    requests:
      storage: 1Mi
