---
apiVersion: v1
kind: Service
metadata:
  name: external-wg
  namespace: monitoring
  labels:
    app: external-wg
spec:
  ports:
    - name: wg-exporter
      port: 9586
  type: ExternalName
  externalName: 10.99.97.1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-wg
  namespace: monitoring
  labels:
    app: external-wg
subsets:
  - addresses:
      - ip: 10.99.97.1
    ports:
      - name: wg-exporter
        port: 9586
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wg
  namespace: monitoring
  labels:
    app: external-wg
    release: prometheus
    jobLabel: wg-exporter
spec:
  selector:
    matchLabels:
      app: external-wg
  endpoints:
    - port: wg-exporter
      interval: 60s
  jobLabel: jobLabel
---
apiVersion: v1
kind: Service
metadata:
  name: external-wgnode
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    release: kube-prometheus-stack
spec:
  ports:
    - name: http-metrics
      port: 9100
  type: ExternalName
  externalName: 10.99.97.1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-wgnode
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    release: kube-prometheus-stack
subsets:
  - addresses:
      - ip: 10.99.97.1
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
