---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: pgo-s3-creds
spec:
  externalSecretName: pgo-s3-creds

  namespaceSelector:
    matchLabels:
      pgo-enabled: 'true'

  refreshTime: 1m

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect

    target:
      name: pgo-s3-creds
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          s3.conf: |
            [global]
            repo1-s3-key={{ .s3_AWS_ACCESS_KEY_ID }}
            repo1-s3-key-secret={{ .s3_AWS_SECRET_ACCESS_KEY }}

    dataFrom:
      - extract:
          key: pgo-s3-creds
        rewrite:
          - regexp:
              source: (.*)
              target: s3_$1
