---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./minecraft-bedrock/ks.yaml
  - ./minecraft-stacia2-expert/ks.yaml
  - ./minecraft-enigmatica10/ks.yaml
  - ./minecraft-games/ks.yaml
