---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-teamspeak
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/media/teamspeak/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-crunchy-postgres-operator
