---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-stacia2-expert
  namespace: games
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
