---
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: etcd-backup
  namespace: backup
actions:
  ectd-backup:
    phases:
      - func: KubeTask
        name: etcd-vmware
        args:
          namespace: backup
          image: ghcr.io/siderolabs/talosctl:v1.0.3
          podOverride:
            containers:
              - name: talosctl
                imagePullPolicy: IfNotPresent
                env:
                  - name: TZ
                    value: Europe/London
                volumeMounts:
                  - name: talosctl-conf
                    mountPath: /config
                  - name: etcd-backup
                    mountPath: /mnt/etcd-backup
            volumes:
              - name: talosctl-conf
                secret:
                  secretName: talosctl-conf
              - name: etcd-backup
                persistentVolumeClaim:
                  claimName: etcd-backup-v1
          command:
            - talosctl
            - --talosconfig
            - /config/config
            - --context
            - ur30-sidero
            - -n
            - 192.168.48.100
            - etcd
            - snapshot
            - /mnt/etcd-backup/ur30-sidero.snapshot
      - func: KubeTask
        name: etcd-sidero
        args:
          namespace: backup
          image: ghcr.io/siderolabs/talosctl:v1.0.3
          podOverride:
            containers:
              - name: talosctl
                imagePullPolicy: IfNotPresent
                env:
                  - name: TZ
                    value: Europe/London
                volumeMounts:
                  - name: talosctl-conf
                    mountPath: /config
                  - name: etcd-backup
                    mountPath: /mnt/etcd-backup
            volumes:
              - name: talosctl-conf
                secret:
                  secretName: talosctl-conf
              - name: etcd-backup
                persistentVolumeClaim:
                  claimName: etcd-backup-v1
          command:
            - talosctl
            - --talosconfig
            - /config/config
            - --context
            - ur30-sidero
            - -n
            - 192.168.48.200
            - etcd
            - snapshot
            - /mnt/etcd-backup/ur30-sidero.snapshot
