---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/radarr
      tag: 5.21.1
      # -- image pull policy
      pullPolicy: IfNotPresent
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: Europe/Moscow
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          external-dns.alpha.kubernetes.io/type: internal
        ingressClassName: external-nginx
        hosts:
          - host: radarr.ur30.ru
            paths:
              - path: /
                pathType: Prefix
    podAnnotations:
      backup.velero.io/backup-volumes: config
      setGateway: 'true'
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: radarr-config-v1
      media:
        enabled: true
        existingClaim: nfs-public-pvc
        mountPath: /media
