---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gitea-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_ACCESS_KEY }}'
        GITEA_OAUTH_KEY_0: '{{ .GITEA_OAUTH_KEY }}'
        GITEA_OAUTH_SECRET_0: '{{ .GITEA_OAUTH_SECRET }}'
        username: '{{ .ADMIN_USERNAME }}'
        password: '{{ .ADMIN_PASSWORD }}'
        SMTP_USERNAME: '{{ .SMTP_USERNAME }}'
        SMTP_PASSWORD: '{{ .SMTP_PASSWORD }}'
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: smtp
