---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: apps
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.com/charts/
      chart: gitea
      version: 11.0.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: "docker.gitea.com"
      repository: gitea
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.23.7"
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    gitea:
      admin:
        existingSecret: gitea-secret
      config:
        APP_NAME: Glants Gitea
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        database:
          DB_TYPE: postgres
          HOST: gitea-pgsql-primary.apps.svc.cluster.local:5432
          NAME: gitea
        queue:
          TYPE: level
        mailer:
          ENABLED: true
          SMTP_PORT: 25
          SMTP_ADDR: mail.ur30.ru
          FROM: "Gitea <gitea@glants.xyz>"
        storage:
          STORAGE_TYPE: minio
          MINIO_ENDPOINT: nas.ur30.ru:30002
          MINIO_BUCKET: gitea
          MINIO_USE_SSL: true
          MINIO_ACCESS_KEY_ID: gitea
        openid:
          ENABLE_OPENID_SIGNIN: false
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
          ACCOUNT_LINKING: auto
        service:
          DISABLE_REGISTRATION: false
          ENABLE_BASIC_AUTHENTICATION: false
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          SHOW_REGISTRATION_BUTTON: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
        cache:
          ADAPTER: memory
        session:
          PROVIDER: db
        server:
          DOMAIN: gitea.glants.xyz
          LFS_START_SERVER: true
          ROOT_URL: "https://gitea.glants.xyz"
          OFFLINE_MODE: false
          DISABLE_SSH: true
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: gitea-pgsql-pguser-gitea
              key: user
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-pgsql-pguser-gitea
              key: password
        - name: GITEA__STORAGE__MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: MINIO_SECRET_ACCESS_KEY
        - name: GITEA__MAILER__USER
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: SMTP_USERNAME
        - name: GITEA__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: SMTP_PASSWORD
      oauth:
        - name: Authentik
          provider: openidConnect
          existingSecret: gitea-secret
          autoDiscoverUrl: https://authentik.glants.xyz/application/o/gitea/.well-known/openid-configuration
          iconUrl: https://authentik.glants.xyz/static/dist/assets/icons/icon.svg
          scopes: email profile gitea
          adminGroup: admin
          groupClaimName: gitea
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    service:
      ssh:
        type: ClusterIP
        port: 22
    ingress:
      enabled: true
      className: external-nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: gitea.glants.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - gitea.glants.xyz
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    persistence:
      enabled: true
      create: false
      mount: true
      claimName: gitea-data-v1
