---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-restic
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/gitea'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gitea
  namespace: apps
spec:
  sourcePVC: gitea-data-v1
  trigger:
    schedule: 0 */12 * * *
  restic:
    copyMethod: Clone
    pruneIntervalDays: 7
    repository: gitea-restic-secret
    retain:
      hourly: 3
      daily: 7
    volumeSnapshotClassName: freenas-nfs-csi
    storageClassName: freenas-nfs-csi
    cacheStorageClassName: freenas-nfs-csi
