---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config-v1
  namespace: apps
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
