---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: element-web
  namespace: matrix
spec:
  interval: 15m
  chart:
    spec:
      chart: element-web
      version: 1.4.16
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    image:
      repository: vectorim/element-web
      pullPolicy: IfNotPresent
      tag: "v1.11.105"

    defaultServer:
      url: https://matrix.glants.xyz
      name: glants.xyz
      identity_url: https://vector.im

    config:
      jitsi:
        preferred_domain: jitsi.glants.xyz
    nginxConfig: |-
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
      add_header Content-Security-Policy "frame-ancestors 'self'";

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      hosts:
        - element.glants.xyz
      tls:
        - secretName: element-web-tls
          hosts:
            - element.glants.xyz
      className: external-nginx

    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
