---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis
  namespace: apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ocis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OCIS_JWT_SECRET: '{{ .OCIS_JWT_SECRET }}'
        STORAGE_USERS_S3NG_ACCESS_KEY: '{{ .AWS_ACCESS_KEY_ID }}'
        STORAGE_USERS_S3NG_SECRET_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: ocis
    - extract:
        key: nas-s3
