---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542 # gladius:external-services

        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.6
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.6
            env:
              DEMO_USERS: false
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.glants.xyz
              PROXY_TLS: false
              STORAGE_USERS_DRIVER: s3ng
              STORAGE_SYSTEM_DRIVER: ocis
              STORAGE_USERS_S3NG_ENDPOINT: https://nas.ur30.ru:9000
              STORAGE_USERS_S3NG_REGION: us-east-1
              STORAGE_USERS_S3NG_BUCKET: ocis
              OCIS_OIDC_ISSUER: "https://authentik.glants.xyz/application/o/ocis/"
              WEB_OIDC_METADATA_URL: "https://authentik.glants.xyz/application/o/ocis/.well-known/openid-configuration"
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              OCIS_EXCLUDE_RUN_SERVICES: "idp"
              # Use upstream OIDC provider's .well-known instead of oCIS's, needed for mobile clients to use external OIDC
              PROXY_OIDC_REWRITE_WELLKNOWN: true
              # Auto role assignment
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              PROXY_AUTOPROVISION_ACCOUNTS: true
              WEB_OIDC_SCOPE: "openid profile email groups"
              PROXY_USER_OIDC_CLAIM: "preferred_username"
              PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: files.glants.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ocis-tls
            hosts:
              - files.glants.xyz
    persistence:
      web-config:
        type: configMap
        name: ocis-configmap
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
      config:
        existingClaim: ocis-config-v1
        globalMounts:
          - path: /etc/ocis
            subPath: config
      nfs-data:
        type: nfs
        server: nas.ur30.ru
        path: /mnt/Storinator/ocis
        globalMounts:
          - path: /var/lib/ocis
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
