---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./volsync.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: ocis-configmap
    files:
      - web.yaml=./config/web.yaml
      - csp.yaml=./config/csp.yaml
generatorOptions:
  disableNameSuffixHash: true
