---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-config
  namespace: apps
data:
  freshclam.conf: |-
    ###############
    # General
    ###############

    DatabaseDirectory /data
    UpdateLogFile /dev/stdout
    LogTime yes
    PidFile /run/freshclam.pid
    DatabaseOwner root

    ###############
    # Updates
    ###############

    PrivateMirror pivotal-clamav-mirror.s3.amazonaws.com
    ScriptedUpdates no
    NotifyClamd /etc/clamav/clamd.conf
    Bytecode yes
