---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mailu-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Mailu
        secret-key: '{{ .SECRET_KEY }}'
        INITIAL_PASSWORD: '{{ .INITIAL_PASSWORD }}'
        mariadb-root-password: '{{ .MARIADB_ROOT_PASSWORD }}'
        mariadb-replication-password: '{{ .MARIADB_REPLICATION_PASSWORD }}'
        mariadb-password: '{{ .MARIADB_PASSWORD }}'
        ROUNDCUBE_PASSWORD: '{{ .ROUNDCUBE_PASSWORD }}'
  dataFrom:
    - extract:
        key: mailu
