---
apiVersion: v1
kind: Secret
metadata:
  name: botkube-communications-secret
  namespace: monitoring
data:
  values.yaml: ENC[AES256_GCM,data:vdBVaSApWrgv/mOk9w02XM4fvkv7oD623IRf/yVe12yu+kOLSihH/0xOqB70MNKhQgXSZjWXnRch2fOOcr15djldMz2+TwSOak+hayCbXYvG1F6cd+aoiNfXLbTIKNIaVxdqOCBqsbTmK1d8tT6gQGExvXq6fw+BG2HIJqAqUnmns6ekTw1sWkisIefHd1IEGO9UHSnE5wgpqvC5FqkP2PJo3GHxPYzPaChOSm/jHwYy5904sg9sfSY/Fw9LP3c1tV9LcGbp/EszaZoVdMLIe+xzgNh8ZFU5v7XWHfVNLEwwsTuSDbpUrHlTJ5bDYUM9hqS4vHZT8e560r/3djj38Th4lhGPbBlIhCTfNJPFgGVyA3iapcu0PpbboXoRyLkLELsjgRycRYyctfxI+9BetxiJyiWvXxrBVVGml2WdP9LXYOHolqxRGCHbZ3H0j6OsTysrmCimMYw67C0a6xnrgmgZoqG8Zw5BQc9u25ZliIWOzZkM5/2hkueavNzsZqljtYlQaRTZ8sWUpS1MatJ+3hE3MaTVgtHM6b+wDHEj1Jzle/pkD7Ffij7tM4aRRgTDy6o6gSrAKxy4PAfqO3Nkf4rHNBz1YCL9q0s8ynkA7tIi0J8CSI7ZGsG9ffYx6xpWQE4vaAE+RFyJA7CktFO1FExySFBtyeIyO7cQp4s8HCpRos710Q5z+mdACELmE4raotAmqEF5MSE4DfHxpvkuLe0En7W9,iv:O7fXTqjZsTGpKxg0Ms5ri96QwBcG3PDBK9dFJTbPMhU=,tag:shr1lVlhpX59qEkhcRVMbw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-06-09T11:09:54Z'
  mac: ENC[AES256_GCM,data:13B/rsJEMSYOeKYJwLYn+aE8E4qIv2KOi8wCztLFIC0bQO1y+kXfDtRBPIBu6F+ZXO0Z8lnDaGYVMEPKNtBQFsmfC6IAD/wKRjSA4ZZE5D1XEv4mINuxeQynQexOV0Tmm2cGgAeFHDbBEHBsyRSxWW89aKXAMi4o9ZPztZ0xcf8=,iv:1EMLRkV/+0fAbp4tjU0pcNsjPoiXf0PSY5ZqsxEs/1g=,tag:W/AeFPuHIDwB+ohVtPo/OA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
