---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  namespace: smarthome
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: asterisk-config
      labels:
        app: asterisk
    spec:
      volumes:
        - name: asterisk-cert
          secret:
            secretName: asterisk-cert-secret
        - name: asterisk-config
          configMap:
            name: asterisk-config
            items:
              - key: extensions.conf
                path: extensions.conf
              - key: modules.conf
                path: modules.conf
              - key: rtp.conf
                path: rtp.conf
              - key: pjsip.conf
                path: pjsip.conf
              - key: logger.conf
                path: logger.conf
              - key: http.conf
                path: http.conf
      containers:
        - name: asterisk
          image: christoofar/asterisk:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/asterisk
              name: asterisk-config
            - mountPath: /etc/asterisk/keys
              name: asterisk-cert
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 300m
              memory: 512Mi
          ports:
            - name: iax
              containerPort: 4569
              protocol: UDP
            - name: sip
              containerPort: 5060
              protocol: UDP
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: https
              containerPort: 8089
              protocol: TCP
            - name: rtp-10000
              containerPort: 10000
              protocol: UDP
            - name: rtp-10001
              containerPort: 10001
              protocol: UDP
            - name: rtp-10002
              containerPort: 10002
              protocol: UDP
            - name: rtp-10003
              containerPort: 10003
              protocol: UDP
            - name: rtp-10004
              containerPort: 10004
              protocol: UDP
            - name: rtp-10005
              containerPort: 10005
              protocol: UDP
            - name: rtp-10006
              containerPort: 10006
              protocol: UDP
            - name: rtp-10007
              containerPort: 10007
              protocol: UDP
            - name: rtp-10008
              containerPort: 10008
              protocol: UDP
            - name: rtp-10009
              containerPort: 10009
              protocol: UDP
            - name: rtp-10010
              containerPort: 10010
              protocol: UDP
            - name: rtp-10011
              containerPort: 10011
              protocol: UDP
            - name: rtp-10012
              containerPort: 10012
              protocol: UDP
            - name: rtp-10013
              containerPort: 10013
              protocol: UDP
            - name: rtp-10014
              containerPort: 10014
              protocol: UDP
            - name: rtp-10015
              containerPort: 10015
              protocol: UDP
            - name: rtp-10016
              containerPort: 10016
              protocol: UDP
            - name: rtp-10017
              containerPort: 10017
              protocol: UDP
            - name: rtp-10018
              containerPort: 10018
              protocol: UDP
            - name: rtp-10019
              containerPort: 10019
              protocol: UDP
            - name: rtp-10020
              containerPort: 10020
              protocol: UDP
            - name: rtp-10021
              containerPort: 10021
              protocol: UDP
            - name: rtp-10022
              containerPort: 10022
              protocol: UDP
            - name: rtp-10023
              containerPort: 10023
              protocol: UDP
            - name: rtp-10024
              containerPort: 10024
              protocol: UDP
            - name: rtp-10025
              containerPort: 10025
              protocol: UDP
            - name: rtp-10026
              containerPort: 10026
              protocol: UDP
            - name: rtp-10027
              containerPort: 10027
              protocol: UDP
            - name: rtp-10028
              containerPort: 10028
              protocol: UDP
            - name: rtp-10029
              containerPort: 10029
              protocol: UDP
            - name: rtp-10030
              containerPort: 10030
              protocol: UDP
            - name: rtp-10031
              containerPort: 10031
              protocol: UDP
            - name: rtp-10032
              containerPort: 10032
              protocol: UDP
            - name: rtp-10033
              containerPort: 10033
              protocol: UDP
            - name: rtp-10034
              containerPort: 10034
              protocol: UDP
            - name: rtp-10035
              containerPort: 10035
              protocol: UDP
            - name: rtp-10036
              containerPort: 10036
              protocol: UDP
            - name: rtp-10037
              containerPort: 10037
              protocol: UDP
            - name: rtp-10038
              containerPort: 10038
              protocol: UDP
            - name: rtp-10039
              containerPort: 10039
              protocol: UDP
            - name: rtp-10040
              containerPort: 10040
              protocol: UDP
            - name: rtp-10041
              containerPort: 10041
              protocol: UDP
            - name: rtp-10042
              containerPort: 10042
              protocol: UDP
            - name: rtp-10043
              containerPort: 10043
              protocol: UDP
            - name: rtp-10044
              containerPort: 10044
              protocol: UDP
            - name: rtp-10045
              containerPort: 10045
              protocol: UDP
            - name: rtp-10046
              containerPort: 10046
              protocol: UDP
            - name: rtp-10047
              containerPort: 10047
              protocol: UDP
            - name: rtp-10048
              containerPort: 10048
              protocol: UDP
            - name: rtp-10049
              containerPort: 10049
              protocol: UDP
            - name: rtp-10050
              containerPort: 10050
              protocol: UDP
            - name: rtp-10051
              containerPort: 10051
              protocol: UDP
            - name: rtp-10052
              containerPort: 10052
              protocol: UDP
            - name: rtp-10053
              containerPort: 10053
              protocol: UDP
            - name: rtp-10054
              containerPort: 10054
              protocol: UDP
            - name: rtp-10055
              containerPort: 10055
              protocol: UDP
            - name: rtp-10056
              containerPort: 10056
              protocol: UDP
            - name: rtp-10057
              containerPort: 10057
              protocol: UDP
            - name: rtp-10058
              containerPort: 10058
              protocol: UDP
            - name: rtp-10059
              containerPort: 10059
              protocol: UDP
            - name: rtp-10060
              containerPort: 10060
              protocol: UDP
            - name: rtp-10061
              containerPort: 10061
              protocol: UDP
            - name: rtp-10062
              containerPort: 10062
              protocol: UDP
            - name: rtp-10063
              containerPort: 10063
              protocol: UDP
            - name: rtp-10064
              containerPort: 10064
              protocol: UDP
            - name: rtp-10065
              containerPort: 10065
              protocol: UDP
            - name: rtp-10066
              containerPort: 10066
              protocol: UDP
            - name: rtp-10067
              containerPort: 10067
              protocol: UDP
            - name: rtp-10068
              containerPort: 10068
              protocol: UDP
            - name: rtp-10069
              containerPort: 10069
              protocol: UDP
            - name: rtp-10070
              containerPort: 10070
              protocol: UDP
            - name: rtp-10071
              containerPort: 10071
              protocol: UDP
            - name: rtp-10072
              containerPort: 10072
              protocol: UDP
            - name: rtp-10073
              containerPort: 10073
              protocol: UDP
            - name: rtp-10074
              containerPort: 10074
              protocol: UDP
            - name: rtp-10075
              containerPort: 10075
              protocol: UDP
            - name: rtp-10076
              containerPort: 10076
              protocol: UDP
            - name: rtp-10077
              containerPort: 10077
              protocol: UDP
            - name: rtp-10078
              containerPort: 10078
              protocol: UDP
            - name: rtp-10079
              containerPort: 10079
              protocol: UDP
            - name: rtp-10080
              containerPort: 10080
              protocol: UDP
            - name: rtp-10081
              containerPort: 10081
              protocol: UDP
            - name: rtp-10082
              containerPort: 10082
              protocol: UDP
            - name: rtp-10083
              containerPort: 10083
              protocol: UDP
            - name: rtp-10084
              containerPort: 10084
              protocol: UDP
            - name: rtp-10085
              containerPort: 10085
              protocol: UDP
            - name: rtp-10086
              containerPort: 10086
              protocol: UDP
            - name: rtp-10087
              containerPort: 10087
              protocol: UDP
            - name: rtp-10088
              containerPort: 10088
              protocol: UDP
            - name: rtp-10089
              containerPort: 10089
              protocol: UDP
            - name: rtp-10090
              containerPort: 10090
              protocol: UDP
            - name: rtp-10091
              containerPort: 10091
              protocol: UDP
            - name: rtp-10092
              containerPort: 10092
              protocol: UDP
            - name: rtp-10093
              containerPort: 10093
              protocol: UDP
            - name: rtp-10094
              containerPort: 10094
              protocol: UDP
            - name: rtp-10095
              containerPort: 10095
              protocol: UDP
            - name: rtp-10096
              containerPort: 10096
              protocol: UDP
            - name: rtp-10097
              containerPort: 10097
              protocol: UDP
            - name: rtp-10098
              containerPort: 10098
              protocol: UDP
            - name: rtp-10099
              containerPort: 10099
              protocol: UDP
            - name: rtp-10100
              containerPort: 10100
              protocol: UDP
