---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uisp-config-v2
  namespace: networking
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
