---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uisp-config-v1
  namespace: networking
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
