---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: apps
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pgsql.home
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 172.16.32.100
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v15
    role: primary
