---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: smarthome-pgsql
  namespace: smarthome
spec:
  postgresVersion: 15
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        repo1-path: /smarthome/repo1
        repo1-s3-uri-style: path
        repo1-storage-port: '30002'
      repo:
        name: repo1
        s3:
          bucket: crunchy-postgres
          endpoint: nas.glants.xyz
          region: us-east-1
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all all md5
  instances:
    - name: postgres
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: home-assistant
      databases:
        - home-assistant
      options: SUPERUSER
    - name: teslamate
      databases:
        - teslamate
      options: SUPERUSER
    - name: atuin
      databases:
        - atuin
      password:
        type: AlphaNumeric
      options: SUPERUSER
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: '14'
        repo1-retention-full-type: time
        repo1-path: /smarthome/repo1
        repo1-s3-uri-style: path
        repo1-storage-port: '30002'
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: 0 1 * * 0
            differential: 0 1 * * 1-6
          s3:
            bucket: crunchy-postgres
            endpoint: nas.glants.xyz
            region: us-east-1
