---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-v2
  namespace: media
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 20Gi
