---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: apps
spec:
  schedule: 0 3 * * *
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: etcd-sidero
              image: ghcr.io/siderolabs/talosctl:v1.1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: Europe/London
              volumeMounts:
                - name: talosctl-conf
                  mountPath: /config
                - name: etcd-backup
                  mountPath: /mnt/etcd-backup
              command:
                - /talosctl
                - --talosconfig
                - /config/config
                - --context
                - ur30-sidero
                - -n
                - 192.168.48.200
                - etcd
                - snapshot
                - /mnt/etcd-backup/ur30-sidero.snapshot
          containers:
            - name: etcd-vmware
              image: ghcr.io/siderolabs/talosctl:v1.1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: Europe/London
              volumeMounts:
                - name: talosctl-conf
                  mountPath: /config
                - name: etcd-backup
                  mountPath: /mnt/etcd-backup
              command:
                - /talosctl
                - --talosconfig
                - /config/config
                - --context
                - ur30-vmware
                - -n
                - 192.168.48.100
                - etcd
                - snapshot
                - /mnt/etcd-backup/ur30-vmware.snapshot
          volumes:
            - name: talosctl-conf
              secret:
                secretName: talosctl-conf
            - name: etcd-backup
              persistentVolumeClaim:
                claimName: etcd-backup-v1
          restartPolicy: OnFailure
