---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-v1
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 4Gi
