---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: torrserver
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: torrserver
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: smailkoz/torrserver
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag
      tag: 1.0.111
    hostNetwork: true
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: torrserver.home
            paths:
              - path: /
                pathType: Prefix

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        existingClaim: torrserver-data-v1
