---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name netbox-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # netbox
        ldap_bind_password: '{{ .LDAP_BIND_PASSWORD }}'
        napalm_password: ''
        email_password: '{{ .SMTP_PASSWORD }}'
        secret_key: '{{ .SECRET_KEY }}'
        superuser_password: '{{ .SUPERUSER_PASSWORD }}'
        superuser_api_token: '{{ .SUPERUSER_API_TOKEN }}'
        db_password: '{{ .DB_PASSWORD }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        redis_tasks_password: '{{ .REDIS_PASSWORD }}'
        redis_cache_password: '{{ .REDIS_PASSWORD }}'
        redis-password: '{{ .REDIS_PASSWORD }}'
        OIDC_SECRET: '{{ .OIDC_SECRET }}'
  dataFrom:
    - extract:
        key: netbox
    - extract:
        key: smtp
