---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: infra
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.13.15
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.2.0-debian-10-r44
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.40.4
    persistence:
      ## @param persistence.enabled Enable persistence using PVC
      ##
      enabled: true
      existingClaim: postgres-data-v1
    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 2048Mi
        cpu: '1'
      limits:
        memory: 8192Mi
        cpu: '4'
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: false
  valuesFrom:
    - kind: Secret
      name: postgres-helm-values
      valuesKey: values.yaml
      optional: false
