---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-mysql-v1
  namespace: media
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
