---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.13.4
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.13.4
