---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      config:
        custom-http-errors: 404,401,403,500,503
        hsts-max-age: '31449600'
      use-forwarded-headers: 'true'
      admissionWebhooks:
        enabled: false
      service:
        loadBalancerIP: 172.16.32.1
        externalTrafficPolicy: Local
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: kube-system
        prometheusRule:
          enabled: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ingress-nginx
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 2Gi
          cpu: 4
    defaultBackend:
      enabled: true
      image:
        repository: raspbernetes/custom-error-pages
        tag: latest
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 250Mi
