---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: multus-cni
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/multus-cni
      tag: 4.0.2-debian-11-r124
    CNIVersion: 0.3.1
    hostCNIBinDir: /opt/cni/bin
    hostCNINetDir: /etc/cni/net.d
    # https://github.com/k8snetworkplumbingwg/multus-cni/issues/1089
    initContainers:
      - name: delete-multus-conf-workaround
        image: alpine
        command: [rm]
        args:
          - -f
          - /bitnami/multus-cni/host/etc/cni/net.d/00-multus.conf
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /bitnami/multus-cni/host/etc/cni/net.d
            name: cni-net-dir
