---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2
      pullPolicy: IfNotPresent

    tolerations:
      - effect: NoSchedule
        operator: Exists

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.3.0
        pullPolicy: IfNotPresent

      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin

      version: 0.3.1

    hostPaths:
      netns: /var/run/netns
