---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '{{ .authentik_GRAFANA_OAUTH_CLIENT_ID }}' # from authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: '{{ .authentik_GRAFANA_OAUTH_CLIENT_SECRET }}' # from authentik
  dataFrom:
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: (.*)
            target: authentik_$1
