---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbtools-emonoda-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbtools-emonoda-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          core:
              client: qbittorrent
              torrents_dir: /downloads/TORRENTS/.Torrents/Completed
          client:
              url: http://qbittorrent:8080
          trackers:
              rutracker.org:
                  user: {{ .RUTRACKER_LOGIN }}
                  passwd: {{ .RUTRACKER_PASSWORD }}
              nnm-club.me:
                  user: {{ .NNMCLUB_LOGIN }}
                  passwd: {{ .NNMCLUB_PASSWORD }}

          confetti:
              telegram:
                  token: {{ .TELEGRAM_TOKEN }}
                  chats: [{{ .TELEGRAM_CHAT }}]

  dataFrom:
    - extract:
        key: qbittorrent
