---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./external-services/ks.yaml
  - ./externaldns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./cloudflared/ks.yaml
