---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./bind9/ks.yaml
  - ./blocky/ks.yaml
  - ./external-services/ks.yaml
  - ./externaldns-internal/ks.yaml
  - ./kea/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./cloudflared/ks.yaml
