---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: networking
spec:
  selector:
    app: bind9
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  type: LoadBalancer
  loadBalancerIP: 192.168.40.14
