---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-descheduler-charts
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      botkube.io/disable: 'true'
    kind: Deployment
    deschedulingInterval: 1m
    cmdOptions:
      v: 3
    deschedulerPolicy:
      evictLocalStoragePods: false
      strategies:
        PodLifeTime:
          enabled: true
          params:
            podLifeTime:
              states:
                - Pending
                - PodInitializing
                - ContainerCreating
              maxPodLifeTimeSeconds: 3600
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            includeSoftConstraints: true
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
          params:
            nodeFit: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 35
                memory: 35
              targetThresholds:
                cpu: 40
                memory: 40
        RemoveFailedPods:
          enabled: true
          params:
            failedPods:
              reasons:
                - NodeShutdown
                - ImagePullBackOff
                - CreateContainerConfigError
              includingInitContainers: true
              excludeOwnerKinds:
                - Job
              minPodLifetimeSeconds: 3600
        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 100
              includingInitContainers: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true
