---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: image=ghcr.io/cloudnative-pg/cloudnative-pg type=docker
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.24.1/config/crd/bases/postgresql.cnpg.io_backups.yaml
  # renovate: image=ghcr.io/cloudnative-pg/cloudnative-pg type=docker
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.24.1/config/crd/bases/postgresql.cnpg.io_clusters.yaml
  # renovate: image=ghcr.io/cloudnative-pg/cloudnative-pg type=docker
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.24.1/config/crd/bases/postgresql.cnpg.io_poolers.yaml
  # renovate: image=ghcr.io/cloudnative-pg/cloudnative-pg type=docker
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.24.1/config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
commonAnnotations:
  meta.helm.sh/release-name: cloudnative-pg
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
