---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: powerdns
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Moscow
    image:
      repository: smailkoz/powerdns
      tag: 4.5.2
      pullPolicy: Always
    replicaCount: 1
    strategyType: Recreate
    service:
      loadBalancerIP: 172.16.32.2
      annotations:
        metallb.universe.tf/allow-shared-ip: powerdns
      type: LoadBalancer
      port: 53
    powerdns:
      domain: home
      config:
        dnsupdate: yes
        allow-dnsupdate-from: 10.0.0.0/8 192.168.30.0/24
        webserver: yes
        webserver-port: 8081
      postgres:
        username: pdns
        database: pdns
      dnssec: false
    mariadb:
      enabled: false
    postgresql:
      enabled: true
      image:
        repository: arm64v8/postgres
        tag: 13.6
      postgresqlUsername: pdns
      postgresqlDatabase: pdns
      persistence:
        enabled: true
        existingClaim: powerdns-postgres-v1
    probes:
      liveness:
        enabled: true
      readiness:
        enabled: true
      startup:
        enabled: false
  valuesFrom:
    - kind: Secret
      name: powerdns-helm-values
      valuesKey: values.yaml
      optional: false
