---
apiVersion: v1
kind: Secret
metadata:
  name: powerdns-helm-values
  namespace: default
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:oYc+LbNlbNuGB7QPw/SHwdWytWp+k9i+QpL3h39bvQvqS0lws0aEC8CYkIEUqRujYaw2KNUf0x5ir9YQ7rFmW6YWDbViS2hfBblwyDod7/FK0UbPJD/Jm5L5ABgzMYq4LolfmulGAQIqQZ3rK/rquDLjtVQR1Ltt0Ig1FP1hySyWT1sIJOJY4xYyulai+ZzkIPXwEC85BI4wGZsNWWP6Eosk+7R0HHb4fvmmjYIBRSmpZhXptzls8K3sUoaA0R/SSmDED35Q/eGFdIvhZRGNmLhenXQwxgDqzatLsEdTpQ5dnSWPWJWtlyGKmvAVOl5q,iv:IRnzodmvP4kb7rKt4uAEYFTkz438JukeoNdGhXRBHvk=,tag:K1sBO9jSRHHnHRyf8ndi7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-06-09T12:29:50Z'
  mac: ENC[AES256_GCM,data:qicixgJeVr8ITNwzobT3SM1iiHCEp2TJYvoX+NjT8JRoqigUbOO/QepO8+/O/as8jtMaJ5/cKk8PkCRh5Ch5L8IZ+YHh8UfJCZEj/eEr6r7lxTDPMK5+F6tAld+Euvg9Ztb74sQXg/GxcnhrmKOl/9vUfC03/TM3OXYJyNO6Ttc=,iv:KqG3qaITh19+RTLI7Dipb0ooIZgpYLIfVrc68Mu/Ktc=,tag:zzTo6TmmEeqAbJN6DN6vjg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
