---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./truenas-nfs-csi/ks.yaml
  - ./truenas-icssi-csi/ks.yaml
