---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-providers
  namespace: infra
spec:
  secretName: authentik-providers-tls
  isCA: false
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - authentik.infra.svc.cluster.local
    - authentik.gearage.ru
    - ldap.gearage.ru
    - ldap.ur30.ru
    - authentik
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: subterra-ca
