---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-providers
  namespace: infra
spec:
  secretName: authentik-providers-tls
  isCA: false
  duration: 26298h0m0s # 3 years
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - authentik.infra.svc.cluster.local
    - authentik.glants.xyz
    - ldap.ur30.ru
    - authentik
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: subterra-ca
