---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pgsql-v1
  namespace: infra
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
