---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-main
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  virtualRouters:
    - localASN: 65005
      exportPodCIDR: false
      serviceSelector:
        matchExpressions:
          - {key: thisFakeSelector, operator: NotIn, values: [will-match-and-announce-all-services]}
      neighbors:
        - peerAddress: 172.16.30.1/32
          peerASN: 65001
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: 172.16.32.0/20
