---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io
      chart: cilium
      version: 1.16.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    bgp:
      enabled: false
    bgpControlPlane:
      enabled: true
    hubble:
      metrics:
        serviceMonitor:
          enabled: true

      relay:
        prometheus:
          serviceMonitor:
            enabled: true

      ui:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          className: internal-nginx
          hosts:
            - hubble-ui.home

    prometheus:
      serviceMonitor:
        enabled: true

    operator:
      prometheus:
        serviceMonitor:
          enabled: true
