---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jitsi-secret
  namespace: matrix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jitsi-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: jitsi
