---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jitsi
  namespace: matrix
spec:
  interval: 15m
  chart:
    spec:
      chart: jitsi-meet
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: jitsi-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    enableAuth: false
    enableGuests: true

    publicURL: jitsi.glants.xyz
    tz: Europe/Moscow

    image:
      pullPolicy: IfNotPresent

    websockets:
      colibri:
        enabled: true
      xmpp:
        enabled: true

    web:
      replicaCount: 1
      image:
        repository: jitsi/web

      ingress:
        enabled: true
        ingressClassName: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        hosts:
          - host: meet.glants.xyz
            paths: ['/']
        tls:
          - secretName: jitsi-tls
            hosts:
              - meet.glants.xyz
    jicofo:
      replicaCount: 1
      image:
        repository: jitsi/jicofo

    jvb:
      replicaCount: 1
      image:
        repository: jitsi/jvb
      publicIPs:
        - 193.41.79.236
      UDPPort: 10000
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          io.cilium/lb-ipam-ips: 192.168.40.21
      metrics:
        enabled: true
    prosody:
      enabled: true
      persistence:
        enabled: true
        size: 3G
        storageClassName: freenas-iscsi-csi
