---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jitsi
  namespace: matrix
spec:
  interval: 15m
  chart:
    spec:
      chart: jitsi
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: element-jitsi-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    shardCount: 1
    ingress:
      enabled: true
      hosts:
        - jitsi.glants.xyz
      class: external-nginx
      tls:
        enabled: true
        secretName: jitsi-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
    jvb:
      sysctlDaemonSetEnable: false
      advertiseIP: 193.41.79.236
    web:
      customConfig: false
      customUi: false
    uvs:
      enable: true
      homeserverUrl: https://matrix.glants.xyz
    createSecret: false
    TZ: Europe/Moscow

    JVB_STUN_SERVERS: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    secretName: jitsi-secret
