---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/charts/metallb/charts/crds/templates/crds.yaml
