---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_addresspools.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_ipaddresspools.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_bgppeers.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_bfdprofiles.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_bgpadvertisements.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_l2advertisements.yaml
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/bases/metallb.io_communities.yaml
commonAnnotations:
  meta.helm.sh/release-namespace: metallb-system
  app.kubernetes.io/managed-by: Helm
  meta.helm.sh/release-name: metallb
patchesStrategicMerge:
  # renovate: image=quay.io/metallb/controller type=docker
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/crd/crd-conversion-patch.yaml
