---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://metallb.github.io/metallb chart=metallb type=helm
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.10/charts/metallb/charts/crds/templates/crds.yaml
