---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-public-pv
  namespace: media
spec:
  storageClassName: public
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: /mnt/Storinator/Public
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-public-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: public
  resources:
    requests:
      storage: 1Mi
