---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: backup
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 4.5.15
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    eula:
      accept: true
      company: ur30
      email: mglants@users.noreply.github.com
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      class: nginx
      host: k10.ur30.local
      annotations:
        kubernetes.io/tls-acme: 'true'
        cert-manager.io/cluster-issuer: ur30local-ca
      urlPath: k10
      tls:
        enabled: true
        secretName: k10-ur30-local-crt-secret
    grafana:
      enabled: false
