---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: media
  namespace: backup
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: nfs-backup-pv
      path: media
    credential:
      secretType: ''
      secret:
        apiVersion: ''
        kind: ''
        name: ''
        namespace: ''
  type: Location
