---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.timescale.com
      chart: timescaledb-single
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: timescale-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    image:
      repository: timescale/timescaledb-ha
      tag: pg14.3-ts2.7.0-p0
    persistentVolumes:
      data:
        enabled: true
        size: 8Gi
        subPath: ''
        mountPath: /var/lib/postgresql
        annotations: {}
        accessModes:
          - ReadWriteOnce
      wal:
        enabled: true
        size: 1Gi
        subPath: ''
        mountPath: /var/lib/postgresql/wal
        annotations: {}
        accessModes:
          - ReadWriteOnce
  valuesFrom:
    - kind: Secret
      name: timescaledb-helm-values
      valuesKey: values.yaml
      optional: false
