---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-ca
  namespace: cert-manager
spec:
  secretName: home-ca-secret
  duration: 8736h0m0s # 1 year
  renewBefore: 240h0m0s # 10 days
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
  commonName: home-ca
  usages:
    - cert sign
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: home-ca
  namespace: cert-manager
spec:
  ca:
    secretName: home-ca-secret
