---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: media
  namespace: backup
spec:
  frequency: '@daily'
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - media
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - matchExpressions:
                - key: kasten.io/backup-volume
                  operator: In
                  values:
                    - enabled
        profile:
          name: media
          namespace: backup
    - action: export
      exportParameters:
        frequency: '@daily'
        profile:
          name: media
          namespace: backup
        hooks:
          onSuccess:
            blueprint: media
            actionName: post-export
        migrationToken:
          name: media-migration-token
          namespace: backup
        exportData:
          enabled: true
