---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: networking
  namespace: backup
spec:
  frequency: '@daily'
  retention:
    daily: 1
    weekly: 0
    monthly: 0
    yearly: 0
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - networking
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - matchExpressions:
                - key: kasten.io/backup-volume
                  operator: In
                  values:
                    - enabled
        profile:
          name: networking
          namespace: backup
    - action: export
      exportParameters:
        frequency: '@daily'
        profile:
          name: networking
          namespace: backup
        hooks:
          onSuccess:
            blueprint: networking
            actionName: post-export
        migrationToken:
          name: migration-token
          namespace: backup
        exportData:
          enabled: true
