---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: www
  namespace: backup
  uid: 476f087b-e20b-4c8a-8e1e-9af6e34558cb
  resourceVersion: '10862511'
  generation: 10
  creationTimestamp: 2022-05-22T23:58:49Z
  labels:
    kustomize.toolkit.fluxcd.io/name: vmware-apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields:
    - manager: kustomize-controller
      operation: Apply
      apiVersion: config.kio.kasten.io/v1alpha1
      time: 2022-05-23T00:27:21Z
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:kustomize.toolkit.fluxcd.io/name: {}
            f:kustomize.toolkit.fluxcd.io/namespace: {}
        f:spec:
          f:frequency: {}
          f:retention:
            .: {}
            f:daily: {}
          f:selector:
            .: {}
            f:matchExpressions: {}
    - manager: Go-http-client
      operation: Update
      apiVersion: config.kio.kasten.io/v1alpha1
      time: 2022-05-23T00:27:21Z
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:actions: {}
        f:status:
          .: {}
          f:hash: {}
          f:specModifiedTime: {}
          f:validation: {}
spec:
  frequency: '@daily'
  retention:
    daily: 3
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - www
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - matchExpressions:
                - key: kasten.io/backup-volume
                  operator: In
                  values:
                    - enabled
        profile:
          name: www
          namespace: backup
    - action: export
      exportParameters:
        frequency: '@daily'
        receiveString: bIzAPpoanmEx93FOhShKhtd9HnASN3LD2wvV9ntrbZc6GcAYrUKYPKGWPp+Hgqo9CzWzzKuNGU+u7zELhTr9xS4B6wwqFMLNcabwp8CR+8KGk4J54HNXZSiu+7CPBKdXfY8ItmBkxMVNibOQ7Nzx/AiUJ+7uwlNAsG7GJWnJzMDXx7NFBE+WvUPSiUH3by1oo+h4VNOkjVgf00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfJa+PK9NzS3DoohV7tGCUo+eQfOGOh0aVFnA4XHJkFG2L+XEr5HH56p3k/MVo91ovOt8KnDpIgM84iTeRFqIUpPgDaBIP5pInnJqmsJHykw3PhtaV6ClmvOdyQK3QQNCT0h+KWs+CSA
        profile:
          name: www
          namespace: backup
        hooks:
          onSuccess:
            blueprint: www
            actionName: post-export
        migrationToken:
          name: www-migration-token-q4v5x
          namespace: backup
        exportData:
          enabled: true
      retention:
        daily: 3
        weekly: 2
        monthly: 3
status:
  validation: Success
  hash: 1475293516
  specModifiedTime: 2022-05-23T00:27:21Z
