---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-restic
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/zigbee2mqtt'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt
  namespace: smarthome
spec:
  sourcePVC: zigbee2mqtt-data-v1
  trigger:
    schedule: 0 */12 * * *
  restic:
    copyMethod: Clone
    pruneIntervalDays: 7
    repository: zigbee2mqtt-restic-secret
    retain:
      hourly: 24
      daily: 7
    volumeSnapshotClassName: freenas-nfs-csi
    storageClassName: freenas-nfs-csi
    cacheStorageClassName: local-hostpath
