---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./rclone/ks.yaml
  - ./talos-backup/ks.yaml
  - ./volsync/ks.yaml
