---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pgo-enabled: 'true'
    routed-gateway: 'true'
    pod-security.kubernetes.io/enforce: privileged
