---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: security
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        subterra: 1
        shared-services: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: security
