---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-enigmatica10-v2
  namespace: games
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
