---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: telegraf-ds
      version: 1.1.10
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repo: telegraf
      tag: 1.19-alpine
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 2Gi
        cpu: 1
    env:
      # This pulls HOSTNAME from the node, not the pod.
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      # In test clusters where hostnames are resolved in /etc/hosts on each node,
      # the HOSTNAME is not resolvable from inside containers
      # So inject the host IP as well
      - name: HOSTIP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: HOST_PROC
        value: /rootfs/proc
      - name: HOST_SYS
        value: /rootfs/sys
    rbac:
      create: true
    serviceAccount:
      create: true
  valuesFrom:
    - kind: Secret
      name: telegraf-helm-values
