---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-exporter-helm-values
  namespace: monitoring
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:d/9WZm2GlZfdTjj9pwXi0K96YlaVf3DP05xcPpjRbUlfjVBnuB+O8KpxH7eQCfaXCGwW/A==,iv:3SfauNsbFmkCa86lxZEDscvLv8Nsq+G/08d6AaY9OTM=,tag:4YU5/7Ls2EruySg0pfYZZw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-05-03T23:53:56Z'
  mac: ENC[AES256_GCM,data:jpZcdCYs+AT79VeFLOAV/An6Jz+xsdWEB+45qeV/6YxJGLsGMvkmwwLSH1TkBoLhmBu15TolpSRCS7C5qsbQOnVIoI9VmvOopRFcy6gIa8Bm4AObK2nePGuXqhDS5xTw2rkcRUgEi2nrR8OtGzanxw/IQ+T4Ma6tY+G+0WQqtTc=,iv:HvVmkPOmzxzFHKKVMX1/8gMA/bPkU1hMt+Qi9qxRBQs=,tag:mflkN0TT+3gryCucA4rdqA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
