---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmware-exporter
  namespace: monitoring
spec:
  endpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      app: vmware-exporter
