---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: windmill
  namespace: apps
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://windmill-labs.github.io/windmill-helm-charts/
      chart: windmill
      version: 2.0.416
      sourceRef:
        kind: HelmRepository
        name: windmill-charts
        namespace: flux-system
      interval: 5m
  values:
    windmill:
      appReplicas: 1
      lspReplicas: 1
      databaseUrlSecretName: windmill-pgsql-pguser-windmill
      databaseUrlSecretKey: uri
      baseDomain: windmill.glants.xyz
      baseProtocol: https
      workerGroups:
        - name: default
          replicas: 1
    ingress:
      # -- enable/disable included ingress resource
      enabled: true
      className: "external-nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts:
            - windmill.glants.xyz
          secretName: windmill-crt
    postgresql:
      # -- enabled included Postgres container for demo purposes only using bitnami
      enabled: false
