---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-csi-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: truenas-csi-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: truenas-csi
