---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-v2
  namespace: monitoring
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: truenas-csi-import-alertmanager-data-v1
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: truenas-csi-import-alertmanager-data-v1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: truenas-csi-import-alertmanager-data-v1
  namespace: monitoring
spec:
  source:
    volumeSnapshotContentName: truenas-csi-import-alertmanager-data-v1
  volumeSnapshotClassName: truenas-csi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: truenas-csi-import-alertmanager-data-v1
spec:
  deletionPolicy: Retain
  driver: csi.truenas.io
  source:
    snapshotHandle: ssd/k8s/nfs/pvc-2fcfd7c5-37e4-4562-b01a-e8f0a0b737eb@truenas-csi-import-alertmanager-data-v1
  volumeSnapshotClassName: truenas-csi
  volumeSnapshotRef:
    name: truenas-csi-import-alertmanager-data-v1
    namespace: monitoring
