---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: vmware
  namespace: flux-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: vmware-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: vmware
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: vmware
  namespace: flux-system
spec:
  controlPlaneEndpoint:
    host: ${CP_IP}
    port: 6443