---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        JWT_SECRET: '{{ .JWT_SECRET }}'
        TYPESENSE_API_KEY: '{{ .TYPESENSE_API_KEY }}'
  dataFrom:
    - extract:
        key: immich
