---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: networking
data:
  named.conf: |
    options {
        directory "/var/cache/bind";
        listen-on { any; };
        allow-query { any; };
        recursion no;
        allow-update { any; };
        max-cache-size 64M;
    };
    zone "home.arpa" {
        type master;
        file "/etc/bind/db.empty";
    };
