---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: networking
data:
  named.conf: |
    options {
        directory "/var/cache/bind";
        listen-on { any; };
        allow-query { any; };
        recursion no;
        allow-update { any; };
        allow-transfer { any; };
        max-cache-size 64M;
    };
    zone "home.arpa" {
        type master;
        file "/etc/bind/home.arpa.db";
    };
    zone "home" {
        type master;
        file "/etc/bind/home.db";
    };
  db_lowttl.empty: |-
    $TTL 60 ; 1 minute
    @       IN      SOA     localhost. root.localhost. (
                                    16         ; serial
                                    60         ; refresh (1 minute)
                                    60         ; retry (1 minute)
                                    60         ; expire (1 minute)
                                    60         ; minimum (1 minute)
                                    )
    @       IN      NS      localhost.
