---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
      annotations:
        configmap.reloader.stakater.com/reload: bind-config
    spec:
      initContainers:
        - name: init-bind
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              set -ex
              cp /mnt/config-map/*.db /mnt/bind/
          volumeMounts:
            - name: bind-zones
              mountPath: /mnt/bind
            - name: bind-config
              mountPath: /mnt/config-map/home.db
              subPath: db_lowttl.empty
            - name: bind-config
              mountPath: /mnt/config-map/home.arpa.db
              subPath: db_normalttl.empty
            - name: bind-config
              mountPath: /mnt/config-map/16.172.in-addr.arpa.db
              subPath: db_normalttl.empty
            - name: bind-config
              mountPath: /mnt/config-map/168.192.in-addr.arpa.db
              subPath: db_normalttl.empty
      containers:
        - name: bind9
          env:
            - name: BIND9_USER
              value: root
          image: ubuntu/bind9:9.18-22.04_beta
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          volumeMounts:
            - name: bind-config
              mountPath: /etc/bind/named.conf
              subPath: named.conf
            - name: bind-data
              mountPath: /var/cache/bind/
            - name: bind-zones
              mountPath: /etc/bind/zones/
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
              - key: db_lowttl.empty
                path: db_lowttl.empty
              - key: db_normalttl.empty
                path: db_normalttl.empty
        - name: bind-data
          emptyDir: {}
        - name: bind-zones
          emptyDir: {}
