---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-internal-secret
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-internal-secret
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: bind
        property: key
