---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  values:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    controller:
      type: daemonset
    image:
      repository: ghcr.io/mglants/smartctl-exporter
      tag: 0.13.0
    service:
      main:
        ports:
          http:
            port: 9633
    serviceMonitor:
      main:
        enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 65Mi

    securityContext:
      privileged: true
      runAsUser: 0

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /dev
