---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  maxHistory: 2
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2025.1.3
    env:
      TZ: Europe/Moscow
      SECRET_RECORDER_DB_URL:
        valueFrom:
          secretKeyRef:
            name: homeassistant-pgsql-pguser-home-assistant
            key: uri
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ha-direct.ur30.ru
          external-dns.alpha.kubernetes.io/type: internal
        type: LoadBalancer
        loadBalancerIP: 192.168.40.15
    ingress:
      main:
        enabled: true
        ingressClassName: external-nginx
        annotations:
          nginx.org/websocket-services: home-assistant
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          external-dns.alpha.kubernetes.io/type: internal
        hosts:
          - host: &host ha.ur30.ru
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homeassistant-tls
    metrics:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      enabled: false
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
        labels: {}
        ## See https://www.ur30.local-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        # bearerTokenSecret:
        #   name: ""
        #   key: ""
      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: false
        labels: {}
        # -- Configure additionial rules for the chart under this key.
        # @default -- See prometheusrules.yaml
        rules: []
        # - alert: HomeAssistantAbsent
        #   annotations:
        #     description: Home Assistant has disappeared from Prometheus service discovery.
        #     summary: Home Assistant is down.
        #   expr: |
        #     absent(up{job=~".*home-assistant.*"} == 1)
        #   for: 5m
        #   labels:
        #     severity: critical
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config-v1
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.96.4
        workingDir: /config
        args:
          - --user-data-dir
          - /config/.vscode
          - --auth
          - none
        ingress:
          enabled: true
          ingressClassName: external-nginx
          annotations:
            kubernetes.io/ingress.class: external-nginx
            nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
            external-dns.alpha.kubernetes.io/type: internal
          hosts:
            - host: ha-vscode.ur30.ru
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    postgresql:
      enabled: false
