---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-v2
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 10Gi
