---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name alertmanager-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: telegram_api_token
      remoteRef:
        key: alertmanager
        property: TELEGRAM_API_TOKEN
