---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: 'true'

    image:
      repository: quay.io/prometheus/alertmanager
      tag: main@sha256:554fd1ae4b42b8317b750364889c5f6feb5becc684f4ed470ce1d3ac48308d2f

    podAnnotations:
      reloader.stakater.com/auto: 'true'

    service:
      main:
        ports:
          http:
            port: 9093

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          external-dns.alpha.kubernetes.io/type: internal
        hosts:
          - host: alertmanager.ur30.ru
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        enabled: true
        type: configMap
        name: alertmanager-configmap
        mountPath: /etc/alertmanager
        readOnly: true
      secrets:
        enabled: true
        type: secret
        name: alertmanager-secret
        mountPath: /etc/secrets
        readOnly: true

    resources:
      requests:
        cpu: 11m
        memory: 50M
      limits:
        memory: 99M

    volumeClaimTemplates:
      - name: storage
        mountPath: /alertmanager
        accessMode: ReadWriteOnce
        size: 50Mi
