---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data-v2
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
