---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-restic
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: karakeep-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/karakeep'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: karakeep
  namespace: apps
spec:
  sourcePVC: karakeep-data-v1
  trigger:
    schedule: 0 */12 * * *
  restic:
    copyMethod: Clone
    pruneIntervalDays: 7
    repository: karakeep-restic-secret
    retain:
      hourly: 24
      daily: 7
    volumeSnapshotClassName: freenas-iscsi-csi
    storageClassName: freenas-iscsi-csi
    cacheStorageClassName: freenas-iscsi-csi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
