---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.18
    controller:
      replicas: 2
      strategy: RollingUpdate
    env:
      TZ: Europe/Moscow
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.32.254
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: dns
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.32.254
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: dns
    metrics:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
        labels: {}
      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: false
        labels: {}
        # -- Configure additionial rules for the chart under this key.
        # @default -- See prometheusrules.yaml
        rules: []
        # - alert: BlockyDisabled
        #   annotations:
        #     description: Blocky's ad blocking has been disabled for 15min.
        #       Please re-enable protection.
        #     summary: Blocky is disabled.
        #   expr: |
        #     blocky_blocking_enabled == 0
        #   for: 15m
        #   labels:
        #     severity: critical
    podAnnotations:
      configmap.reloader.stakater.com/reload: blocky-config
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/name
    #           operator: In
    #           values:
    #           - blocky
    #       topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi
        cpu: 500m
    config: |-
      bootstrapDns: tcp+udp:1.1.1.1
      upstream:
        externalResolvers:
        - tcp-tls:dns3.digitalcourage.de:853
        - tcp-tls:dnsse.alekberg.net:443
        - https://cloudflare-dns.com/dns-query
      conditional:
      # optional: replace domain in the query with other domain before resolver lookup in the mapping
        mapping:
          glants.xyz: udp:172.16.32.2
          home: udp:172.16.32.2
          home.arpa: udp:172.16.32.2
          168.192.in-addr.arpa: udp:172.16.32.2
          16.172.in-addr.arpa: udp:172.16.32.2
      caching:
        minTime: 5m
        maxTime: 30m
        prefetching: true
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://easylist-downloads.adblockplus.org/advblock.txt
          - https://gist.githubusercontent.com/wassname/b594c63222f9e4c83ea23c818440901b/raw/1b0afd2aecf3a099f1681b1cf18fc0e6e2fa116a/Samsung%2520Smart-TV%2520Blocklist%2520Adlist%2520(for%2520PiHole)
          kids:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/billimek/k8s-gitops/master/default/blocky/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
