---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: isponsorblocktv-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: isponsorblocktv-secret
    creationPolicy: Owner
  data:
    - secretKey: config.json
      remoteRef:
        key: isponsorblocktv
        property: config.json
