---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: huawei
spec:
  rules:
      # CC2652R Multiprotocol RF Stick
    - name: huawei
      labels:
        device.feature.node.kubernetes.io/huawei: 'true'
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: {op: In, value: [12d1]}
