---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-smarthome-database
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/berries/apps/smarthome/database/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-crunchy-postgres-operator
    - name: cluster-apps-external-secrets-cluster-secrets
