---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: esphome/esphome
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag
      tag: 2024.7.2

    # -- environment variables.
    # @default -- See below
    env:
      ESPHOME_DASHBOARD_USE_PING: true
      # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
      # ESPHOME_QUICKWIZARD:
      # ESPHOME_IS_HASSIO:
      # DISABLE_HA_AUTHENTICATION:
      # USERNAME:
      # PASSWORD:

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: esphome.home
            paths:
              - path: /
                pathType: Prefix

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config-v1
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |-
        [{
          "name":"multus-iot",
          "namespace": "kube-system",
          "ips": ["172.16.10.6/24"],
          "mac": "ca:21:4e:24:8f:33"
        }]
