---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-v2
  namespace: smarthome
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
