---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.gitops.weave.works
      chart: weave-gitops
      version: 4.0.30
      sourceRef:
        kind: HelmRepository
        name: weaveworks-gitops-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
  # https://docs.gitops.weave.works/docs/references/helm-reference/#values
    adminUser:
      create: true
      username: admin
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
        hajimari.io/icon: mdi:sawtooth-wave
      hosts:
        - host: gitops.ur30.ru
          paths:
            - path: /
              pathType: Prefix
    networkPolicy:
      create: true
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: [admin]
    podAnnotations:
      reloader.stakater.com/auto: 'true'
  valuesFrom:
    - targetPath: adminUser.passwordHash
      kind: Secret
      name: weave-gitops-secret
      valuesKey: ADMIN_PASSWORDHASH
