---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
    region: sh
  name: fd7ce2f2-76f3-41ca-b22e-d88250bddd60
spec:
  pxeBootAlways: true
  accepted: true
  environmentRef:
    namespace: default
    name: sh-amd64
  cpu:
    manufacturer: QEMU
    version: pc-i440fx-5.2
  hostname: berries-control-plane-12
  system:
    family: Unknown
    manufacturer: QEMU
    productName: Standard PC (i440FX + PIIX, 1996)
    serialNumber: Unknown
    skuNumber: Unknown
    version: pc-i440fx-5.2
