---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
    region: sh
  name: 7f966449-6392-4821-a307-9ac122fcd3d0
spec:
  pxeBootAlways: true
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: QEMU
    version: pc-i440fx-5.2
  hostname: berries-control-plane-1
  system:
    family: Unknown
    manufacturer: QEMU
    productName: Standard PC (i440FX + PIIX, 1996)
    serialNumber: Unknown
    skuNumber: Unknown
    version: pc-i440fx-5.2
