---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    worker-node: 'true'
    region: sh
  name: 00d03112-0000-0000-0000-dca632ae446e
spec:
  pxeBootAlways: true
  configPatches:
    - op: add
      path: /machine/network/hostname
      value: berries-worker3
  accepted: true
  environmentRef:
    namespace: default
    name: default-arm64
  hostname: berries-worker-3
  hardware:
    compute:
      processors:
        - manufacturer: Broadcom
          productName: BCM2711 (ARM Cortex-A72)
    system:
      family: Raspberry Pi
      manufacturer: Raspberry Pi Foundation
      productName: Raspberry Pi 4 Model B
      serialNumber: 0000DCA632AE446E
      skuNumber: 0000000000D03112
      version: D03112
