---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    worker-node: 'true'
    region: sh
  name: 00d03114-0000-0000-0000-dca632f9bc1b
spec:
  pxeBootAlways: true
  configPatches:
    - op: add
      path: /machine/network/hostname
      value: talos-0dj-hqc
  accepted: true
  environmentRef:
    namespace: default
    name: default-arm64
  hostname: berries-worker-2
  hardware:
    compute:
      processors:
        - manufacturer: Broadcom
          productName: BCM2711 (ARM Cortex-A72)
    system:
      family: Raspberry Pi
      manufacturer: Raspberry Pi Foundation
      productName: Raspberry Pi 4 Model B
      serialNumber: 0000DCA632F9BC1B
      skuNumber: 0000000000D03114
      version: D03114
