---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
    region: sh
  name: 00d03114-0000-0000-0000-e45f01358531
spec:
  pxeBootAlways: true
  accepted: true
  environmentRef:
    namespace: default
    name: default-arm64
  cpu:
    manufacturer: Broadcom
    version: BCM2711 (ARM Cortex-A72)
  hostname: berries-control-plane-3
  system:
    family: Raspberry Pi
    manufacturer: Raspberry Pi Foundation
    productName: Raspberry Pi 4 Model B
    serialNumber: 0000E45F01358531
    skuNumber: 0000000000D03114
    version: D03114
