---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    master-node: 'true'
    region: sh
  name: 7f966449-6392-4821-a307-9ac122fcd3d0
spec:
  pxeBootAlways: true
  configPatches:
    - op: add
      path: /machine/network/hostname
      value: berries-cp1
  accepted: true
  environmentRef:
    namespace: default
    name: sh-amd64
  hostname: berries-control-plane-1
  hardware:
    compute:
      processors:
        - manufacturer: QEMU
          productName: pc-i440fx-5.2
    system:
      family: Unknown
      manufacturer: QEMU
      productName: Standard PC (i440FX + PIIX, 1996)
      serialNumber: Unknown
      skuNumber: Unknown
      version: pc-i440fx-5.2
