---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vmware-control-plane-1.yaml
  - vmware-control-plane-2.yaml
  - vmware-control-plane-3.yaml
  - vmware-worker-0.yaml
  - vmware-worker-1.yaml
  - berries-control-plane-1.yaml
  - berries-control-plane-2.yaml
  - berries-control-plane-3.yaml
  - berries-worker-1.yaml
  - berries-worker-2.yaml
