apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    worker-node: 'true'
  name: 3e161042-baae-5321-134f-d27791300f1c
spec:
  pxeBootAlways: false
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: GenuineIntel
    version: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  hostname: vmware-worker-0
  system:
    family: Unknown
    manufacturer: VMware, Inc.
    productName: VMware Virtual Platform
    serialNumber: VMware-42 10 16 3e ae ba 21 53-13 4f d2 77 91 30 0f 1c
    skuNumber: Unknown
    version: None