apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    worker-node: 'true'
  name: 8f9d1042-f331-b7fa-b63d-4840bf397230
spec:
  pxeBootAlways: false
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: GenuineIntel
    version: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  hostname: vmware-worker-1
  system:
    family: Unknown
    manufacturer: VMware, Inc.
    productName: VMware Virtual Platform
    serialNumber: VMware-42 10 9d 8f 31 f3 fa b7-b6 3d 48 40 bf 39 72 30
    skuNumber: Unknown
    version: None