---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
  name: 21ea978a-ce50-1831-9665-8c01eda2f5aa
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/vda
  pxeBootAlways: true
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: GenuineIntel
  hostname: vmware-control-plane-3
  system:
    productName: BHYVE
    serialNumber: None
    skuNumber: None
    version: '1.0'
