---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
  name: 096e1042-27b2-c6c6-effe-0f0358c3aa0e
spec:
  pxeBootAlways: false
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: GenuineIntel
    version: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  hostname: vmware-control-plane-1
  system:
    family: Unknown
    manufacturer: VMware, Inc.
    productName: VMware Virtual Platform
    serialNumber: VMware-42 10 6e 09 b2 27 c6 c6-ef fe 0f 03 58 c3 aa 0e
    skuNumber: Unknown
    version: None
