apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    worker-node: 'true'
  name: c65e1042-e4dd-4abf-1db6-8a263bb419cb
spec:
  pxeBootAlways: false
  accepted: true
  environmentRef:
    namespace: default
    name: default-amd64
  cpu:
    manufacturer: GenuineIntel
    version: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  hostname: vmware-control-plane-1
  system:
    family: Unknown
    manufacturer: VMware, Inc.
    productName: VMware Virtual Platform
    serialNumber: VMware-42 10 5e c6 dd e4 bf 4a-1d b6 8a 26 3b b4 19 cb
    skuNumber: Unknown
    version: None