---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vmware-apps
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: vmware-kubeconfig
  interval: 10m0s
  dependsOn:
    - name: vmware-core
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/ur30/vmware/apps
  prune: true
  validation: client
  postBuild:
    substitute: {}
    # substituteFrom:
    #   - kind: Secret
    #     name: cluster-secrets-vmware
    #   - kind: ConfigMap
    #     name: cluster-settings-vmware
  decryption:
    provider: sops
    secretRef:
      name: sops-age
