---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmware-core
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: vmware-kubeconfig
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: vmware-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/ur30/vmware/core
  prune: true
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: sync-settings-vmware
        # substituteFrom:
        #   - kind: Secret
        #     name: cluster-secrets-vmware
  decryption:
    provider: sops
    secretRef:
      name: sops-age
