---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-helm-values
  namespace: smarthome
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:kuRdkgcXNlIDTetVESWSyf/viNDq6KHNMhp/k5N9YI9HUSpTrLvdBjFSEFkTNWQhayrRB32inx46FEcvYfqOBsnRLtp9ycqfQrUEDXpeZaKI2e4uUGoonb+eAj+ldmLXFbzAPN3MY55NUBE2gu+o3qC1MM0oi6t89ySP/DEpx3EbSM6+mcYXLgqQzEWaEeP7HunRuf2PqOzo4es05M/LDoRaVW5FaKjB8Oz9jFxtOT8mpapKzoyL+qSZI/ZhLm6V6B21l/kcddbmtphwwAcwWnBUMWkPnSlZpPlXQIddAwYcrVo+1yiAaA==,iv:iS11AYVrhQkImAr1WNqi4HnJ8Jbml00YQuxoromLsvc=,tag:7c9kxC3sxH2V9OounXZnhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-05-04T00:00:39Z'
  mac: ENC[AES256_GCM,data:n1RE38FzWvrRRmERC129fuJwEJpl321cMOhEhevqsdapjyk90KBbvbWR9mY0SbsC7Ta+6UO3JLs57Zgc4pPXljulim3eEmA4M0mWM9Y49tPiWg7lNX5w25AOvkBbFgoOmKkeTGgF8BsNcDP9KTmM1fOpds3hokhJpRSubS8d35M=,iv:mr/Ke80JRAqB5M71+tkYKHjx0qp8+/A90KpKawzE9eA=,tag:HGKTVnnwLgXObCSBdBJQdQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
