---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp-ruzahouse
  namespace: www
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 14.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/wordpress
      tag: 5.9.3-debian-10-r12
      pullPolicy: IfNotPresent

    wordpressBlogName: User's Blog!
    wordpressTablePrefix: wp_
    wordpressScheme: https
    wordpressConfigureCache: true
    wordpressAutoUpdateLevel: minor
    smtpHost: ''
    smtpPort: ''
    smtpUser: ''
    smtpPassword: ''
    smtpProtocol: ''
    extraVolumes:
      - name: php-args
        configMap:
          name: wp-ruzahouse-php-args
          defaultMode: 0755
    extraVolumeMounts:
      - name: php-args
        mountPath: /opt/bitnami/php/etc/conf.d/
        readOnly: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostname: ruzahouse.ru
      tls: true

    persistence:
      enabled: true
      size: 10Gi

    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: bitnami_wordpress
        username: bn_wordpress
      primary:
        persistence:
          enabled: true
          storageClass: ''
          accessModes:
            - ReadWriteOnce
          size: 8Gi
    memcached:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: wp-ruzahouse-helm-values
      valuesKey: values.yaml
      optional: false
