---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-ruzahouse-wp-v1
  namespace: www
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-ruzahouse-mariadb-v1
  namespace: www
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
