---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: master
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
            # vip:
            #   ip: ${CP_IP}
  selector:
    matchLabels:
      master-node: 'true'