---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: org.democratic-csi.iscsi
    # add note here about volume expansion requirements
    storageClasses:
      - name: freenas-iscsi-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: xfs
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: freenas-iscsi-csi
        parameters:
          detachedSnapshots: 'false'
        secrets:
          snapshotter-secret:

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.48.150
          port: 80
          username: root
          allowInsecure: true
          apiVersion: 2
        zfs:
          cli:
            sudoEnabled: true
          datasetParentName: vmware/k8s/iscsi
          detachedSnapshotsDatasetParentName: vmware/k8s/snap
          zvolCompression: '' # inherit
          zvolDedup: '' # inherit
          zvolEnableReservation: false
          zvolBlocksize: 16K
        iscsi:
          targetPortal: 192.168.48.150:3260
          namePrefix: csi-
          nameSuffix: -subterra
          targetGroups:
            # get the correct ID from the "portal" section in the UI
            - targetGroupPortalGroup: 2
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 1
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: None
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 4096
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: SSD
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ''
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-secret
      valuesKey: API_KEY
