---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nas
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/type: internal
spec:
  endpoints:
    - dnsName: nas.ur30.ru
      recordType: A
      targets:
        - 192.168.48.150
