---
apiVersion: v1
kind: Service
metadata:
  name: nas-s3
  namespace: networking
spec:
  type: ExternalName
  externalName: nas.ur30.ru
  ports:
    - name: s3-hdd
      port: 30002
      targetPort: 30002
    - name: s3-ssd
      port: 30000
      targetPort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-s3-hdd
  namespace: networking
  annotations:
    # upstream speaks HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
    # ignore the weird/self-signed upstream cert
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_verify off;
      proxy_ssl_server_name on;
      proxy_ssl_name nas.ur30.ru;
    # big uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - s3.ur30.ru
      secretName: s3-ur30-tls
  rules:
    - host: s3.ur30.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas-s3
                port:
                  name: s3-hdd
