---
spec:
  template:
    spec:
      volumes:
        - name: tftp-folder
          emptyDir: {}
      initContainers:
        - image: ghcr.io/mglants/raspberrypi4-uefi:sha-6a8da5f
          imagePullPolicy: Always
          name: tftp-folder-setup
          command:
            - cp
          args:
            - -r
            - /tftp
            - /var/lib/sidero/
          volumeMounts:
            - mountPath: /var/lib/sidero/tftp
              name: tftp-folder
      containers:
        - name: manager
          volumeMounts:
            - mountPath: /var/lib/sidero/tftp
              name: tftp-folder
