---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rustdesk.ur30.ru
          external-dns.alpha.kubernetes.io/type: internal
          io.cilium/lb-ipam-ips: 192.168.40.24
        externalTrafficPolicy: Local
        ports:
          api:
            port: 21114
          hbbs-nat:
            port: 21115
          hbbs-id:
            port: &port 21116
          hbbs-id-udp:
            port: *port
            protocol: UDP
          hbbr-relay:
            port: 21117
          hbbs-ws:
            port: 21118
          hbbr-ws:
            port: 21119

    defaultPodOptions:
      securityContext:
        runAsUser: 777
        runAsGroup: 777
        fsGroup: 777
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      log:
        type: emptyDir
        globalMounts:
          - path: /app/runtime
      data:
        existingClaim: rustdesk-data-v1
        globalMounts:
          - path: /db
            subPath: hbbs
          - path: /app/data
            subPath: api
      keys:
        enabled: true
        type: secret
        name: rustdesk-secret
        globalMounts:
          - path: /root/id_ed25519
            subPath: id_ed25519
          - path: /root/id_ed25519.pub
            subPath: id_ed25519.pub

    controllers:
      main:
        containers:
          # main:
          #   image:
          #     repository: ghcr.io/wy414012/rustdesk-server
          #     tag: 1.4.3
          #   command:
          #     - hbbs
          #     - -r localhost:21117
          #   env:
          #     ENCRYPTED_ONLY: "1"
          #     DB_URL: /db/db_v2.sqlite3
          #   resources:
          #     requests:
          #       cpu: 100m
          #       memory: 100Mi
          #     limits:
          #       memory: 1000Mi
          #   probes:
          #     liveness:
          #       enabled: true
          #       custom: true
          #       spec:
          #         tcpSocket:
          #           port: 21116
          #         initialDelaySeconds: 30
          #         periodSeconds: 10
          #         timeoutSeconds: 5
          #         failureThreshold: 3
          # relay:
          #   image:
          #     repository: ghcr.io/wy414012/rustdesk-server
          #     tag: 1.4.3
          #   command:
          #     - hbbr
          #   resources:
          #     requests:
          #       cpu: 100m
          #       memory: 100Mi
          #     limits:
          #       memory: 1000Mi
          #   probes:
          #     liveness:
          #       enabled: true
          #       custom: true
          #       spec:
          #         tcpSocket:
          #           port: 21117
          #         initialDelaySeconds: 30
          #         periodSeconds: 10
          #         timeoutSeconds: 5
          #         failureThreshold: 3
          api:
            image:
              repository: lejianwen/rustdesk-server-s6
              tag: v0.1.2
            env:
              RUSTDESK_API_LANG: en
              RUSTDESK_API_RUSTDESK_ID_SERVER: rustdesk.ur30.ru:21116
              RUSTDESK_API_RUSTDESK_RELAY_SERVER: rustdesk.ur30.ru:21117
              RUSTDESK_API_RUSTDESK_API_SERVER: https://rustdesk-api.ur30.ru
              DB_URL: /db/db_v2.sqlite3
              ENCRYPTED_ONLY: 1
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 1000Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 21114
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
    ingress:
      app:
        className: external-nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
          nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
        hosts:
          - host: rustdesk.ur30.ru
            paths:
              - path: /ws/id
                service:
                  identifier: main
                  port: hbbs-ws
              - path: /ws/relay
                service:
                  identifier: main
                  port: hbbr-ws
              - path: /
                service:
                  identifier: main
                  port: api
          - host: rustdesk-api.ur30.ru
            paths:
              - path: /ws/id
                service:
                  identifier: main
                  port: hbbs-ws
              - path: /ws/relay
                service:
                  identifier: main
                  port: hbbr-ws
              - path: /
                service:
                  identifier: main
                  port: api
        tls:
          - secretName: rustdesk-tls
            hosts:
              - rustdesk-api.ur30.ru
              - rustdesk.ur30.ru
