---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ur30-ca
  namespace: cert-manager
spec:
  secretName: ur30local-ca-secret
  duration: 8736h0m0s # 1 year
  renewBefore: 240h0m0s # 10 days
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
  commonName: ur30local-ca
  usages:
    - cert sign
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ur30local-ca
  namespace: cert-manager
spec:
  ca:
    secretName: ur30local-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ur30local-crt
  namespace: cert-manager
spec:
  secretName: ur30local-crt-secret
  duration: 2160h0m0s # 90 days
  renewBefore: 240h0m0s # 10 days
  issuerRef:
    name: ur30local-ca
    kind: Issuer
  commonName: ur30.local.cluster.local
  dnsNames:
    - ur30.local
    - '*.ur30.local'
