---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name zigbee2mqtt-secret
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: '{{.zigbee2mqtt_EXT_PAN_ID }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: '{{ .zigbee2mqtt_PAN_ID }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: '{{ .zigbee2mqtt_NETWORK_KEY }}'
        # Mosquitto
        ZIGBEE2MQTT_CONFIG_MQTT_USER: '{{ .emqx_MQTT_USERNAME }}'
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: '{{ .emqx_MQTT_PASSWORD }}'
  dataFrom:
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: (.*)
            target: emqx_$1
    - extract:
        key: zigbee2mqtt
      rewrite:
        - regexp:
            source: (.*)
            target: zigbee2mqtt_$1
