---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: apps
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TEST: TEST
      DATA_FOLDER: config
      SMTP_HOST: mail.ur30.ru
      SMTP_FROM: noreply@glants.xyz
      SMTP_FROM_NAME: Vaultwarden
      SMTP_PORT: '465'
      SMTP_SSL: 'true'
      SMTP_EXPLICIT_TLS: 'true'
      SMTP_USERNAME: noreply@glants.xyz
      SMTP_TIMEOUT: 15
      SIGNUPS_ALLOWED: 'false'
      DOMAIN: https://bitwarden.ur30.ru
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-pgsql-pguser-vaultwarden
            key: uri
    envFrom:
      - secretRef:
          name: vaultwarden-secret
    image:
      repository: vaultwarden/server
      pullPolicy: IfNotPresent
      tag: 1.32.7
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        ingressClassName: external-nginx
        hosts:
          - host: bitwarden.ur30.ru
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - secretName: ur30ru-crt-secret

            hosts:
              - bitwarden.ur30.ru
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config-v1
        emptydir:
          enabled: true
    podAnnotations:
      backup.velero.io/backup-volumes: config
