---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: ghcr.io/k8s-at-home/radarr
      # -- image tag
      tag: v4.1.0.6175
      # -- image pull policy
      pullPolicy: IfNotPresent
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: Europe/Moscow
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: radarr.ur30.local
            paths:
              - path: /
                pathType: Prefix
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: radarr-config-v1
      media:
        enabled: true
        existingClaim: nfs-public-pvc
        mountPath: /media
