---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: deluge
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/deluge
      pullPolicy: IfNotPresent
      tag: version-2.0.3-2201906121747ubuntu18.04.1
    env:
      TZ: Europe/Moscow
    service:
      main:
        ports:
          http:
            port: 8112
      daemon:
        type: LoadBalancer
        loadBalancerIP: 192.168.40.6
        annotations:
          metallb.universe.tf/allow-shared-ip: media
        ports:
          daemon:
            primary: false
            port: 58846
            protocol: tcp
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: deluge.ur30.local
            paths:
              - path: /
                pathType: Prefix
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: deluge-config-v1
      downloads:
        enabled: true
        existingClaim: nfs-public-pvc
        mountPath: /downloads
