---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-metrics-server-charts
        namespace: flux-system
      interval: 30m
  values:
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
