---
apiVersion: v1
kind: Secret
metadata:
  name: wp-dachia-helm-values
  namespace: www
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:VeBWJYwC2ja7ImaycMPgVKhCnF8KU2A7k3MifVNO4o7tKj5ZyhxYK27ELavIM0KeS4YVd6zUzPjyqv9eNEe16x7p1vVQddy6XxFNLvuLgqyeZRI1Kq6l0parqD5D1lrASXdskWLkprbnioFZhPmFXtqvQtefoZC5KMw3z2uha7EOIasuUDdJgUUPJRFJMjIsd9sYNlTAEOk6KaD3Pomqgwt2Hf7eD0RrvsEgepkCkdYW1tYP2BsVEgLPNnsnwYldoHa5JQPGL3vusAxhVv0N4Ce27i3QE/uEwO0ig5K3bMyxfXfXw3HRDZDkHnKb4tKe7CncdkgtnO0D7TxAyrIzOsKpg/1cX+wDFxZlk3whLK1lS68nZv74s7alva2lhG4WHBU/25N9J6l1niatA3Grj3APa5gjcDQomQGi5A==,iv:y2sfExmvBzrWC/WF7gxHn3Ft9Unu4RPKRz4cAT4eiuM=,tag:F2vgDAkdvFYyKm04sqof/w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-05-03T23:55:06Z'
  mac: ENC[AES256_GCM,data:JRru0go8v4jLdjuh3Wp3ixBSO61Qzt/t2o1Aze4VlZXxSJ29m6vSOV/JSnyEjo5i3njWuGXPNFJWFOddAXljALzpcw7D15Idw3xFdW7ZwdTSqcIYo3RK1fZaimc9aVw1+c51RAG7dV4E3H87puyR69C5QGa0BBvzeW2+26n0aQw=,iv:oL5YjRLCiJFpWWNcmRz1GREcEiyHQimhzwDCYZ2V4us=,tag:r6iy62RlxdOHTWzk+Zj14Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
