---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mktxp-exporter-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mktxp.conf: |
          [mikrotik]
              hostname = 172.16.30.1
          [default]
              enabled = True
              hostname = localhost
              port = 8728
              username = {{ .mikrotik_USERNAME }}
              password = {{ .mikrotik_PASSWORD }}
              use_ssl = False
              no_ssl_certificate = False
              ssl_certificate_verify = False
              plaintext_login = True
              installed_packages = False
              dhcp = True
              dhcp_lease = True
              connections = True
              connection_stats = False
              interface = True
              route = True
              pool = True
              firewall = True
              neighbor = True
              ipv6_route = False
              ipv6_pool = False
              ipv6_firewall = False
              ipv6_neighbor = False
              poe = False
              monitor = True
              netwatch = True
              public_ip = True
              wireless = False
              wireless_clients = False
              capsman = False
              capsman_clients = False
              kid_control_assigned = False
              kid_control_dynamic = False
              user = True
              queue = True
              bgp = True
              remote_dhcp_entry = None
              use_comments_over_names = True
              check_for_updates = False
  dataFrom:
    - extract:
        key: mikrotik
