---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gammu-tr
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      nodeSelector:
        device.feature.node.kubernetes.io/huawei: 'true'

    controllers:
      gammu:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/mglants/gammu-telegram
              tag: v0.0.3
            env:
              GAMMU_CONNECTION: at115200
              GAMMU_DEVICE: /dev/modem
              GAMMU_NUMBER: 🇹🇷
            envFrom:
              - secretRef:
                  name: gammu-tr-secret
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              privileged: true
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
    persistence:
      data:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /data
      usb:
        enabled: true
        type: hostPath
        hostPathType: CharDevice
        hostPath: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3.4.1:1.0-port0
        globalMounts:
          - path: /dev/modem
