---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graphite-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      graphite-exporter:
        annotations:
          reloader.stakater.com/auto: 'true'

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: prom/graphite-exporter
              tag: v0.15.2
            args:
              - --graphite.mapping-config=/config/graphite-mapping.conf
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 50M
    service:
      app:
        controller: graphite-exporter
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.16.32.11
        ports:
          http:
            port: 9108
          graphite-tcp:
            port: 9109
          graphite-udp:
            port: 9109
            protocol: UDP
    configMaps:
      configmap:
        data:
          graphite-mapping.conf: |-
            mappings:

            ################################################
            # memory mapping
            ################################################

            - match: 'truenas\.(.*)\.system\.ram\.(.*)'
              match_type: "regex"
              name: "physical_memory"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            - match: 'truenas\.(.*)\.mem\.(.*)\.(.*)'
              match_type: "regex"
              name: "memory_${2}"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${3}"

            - match: 'truenas\.(.*)\.system\.swap\.(.*)'
              match_type: "regex"
              name: "swap"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            ################################################
            # disk smart metrics
            ################################################

            - match: 'truenas\.(.*)\.smart\.log\.smart\.disktemp\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_temperature"
              labels:
                job: "truenas"
                instance: "${1}"
                serial: "${2}"

            - match: 'truenas\.(.*)\.smart_log_smart\.disktemp\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_temperature"
              labels:
                job: "truenas"
                instance: "${1}"
                serial: "${2}"

            ################################################
            # disk operation mappings
            ################################################

            - match: 'truenas\.(.*)\.disk\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ops\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io_ops"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ext\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ext_ops\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io_ops"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_backlog\.(.*)\.backlog'
              match_type: "regex"
              name: "disk_io_backlog"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"

            - match: 'truenas\.(.*)\.disk_busy\.(.*)\.busy'
              match_type: "regex"
              name: "disk_busy"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"

            - match: 'truenas\.(.*)\.disk_util\.(.*)\.utilization'
              match_type: "regex"
              name: "disk_utilization"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"

            - match: 'truenas\.(.*)\.disk_mops\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "merged_${3}"

            - match: 'truenas\.(.*)\.disk_ext_mops\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "merged_${3}"

            - match: 'truenas\.(.*)\.disk_iotime\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_iotime"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ext_iotime\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_iotime"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_qops\.(.*)\.operations'
              match_type: "regex"
              name: "disk_qops"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"

            - match: 'truenas\.(.*)\.disk_await\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_await"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ext_await\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_await"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_avgsz\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io_size"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_ext_avgsz\.(.*)\.(.*)'
              match_type: "regex"
              name: "disk_io_size"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.disk_svctm\.(.*)\.svctm'
              match_type: "regex"
              name: "disk_svctm"
              labels:
                job: "truenas"
                instance: "${1}"
                disk: "${2}"

            - match: 'truenas\.(.*)\.system\.io\.(.*)'
              match_type: "regex"
              name: "system_io"
              labels:
                job: "truenas"
                instance: "${1}"
                op: "${2}"

            ################################################
            # CPU mapping
            ################################################

            - match: 'truenas\.(.*)\.system\.intr\.interrupts'
              match_type: "regex"
              name: "interrupts"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "hard"

            - match: 'truenas\.(.*)\.system\.cpu\.softirq'
              match_type: "regex"
              name: "interrupts"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "soft"

            - match: 'truenas\.(.*)\.cpu\.(.*)\.softirq'
              match_type: "regex"
              name: "cpu_softirq"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "${2}"

            - match: 'truenas\.(.*)\.system\.ctxt\.switches'
              match_type: "regex"
              name: "context_switches"
              labels:
                job: "truenas"
                instance: "${1}"

            - match: 'truenas\.(.*)\.system\.cpu\.(.*)'
              match_type: "regex"
              name: "cpu_total"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            - match: 'truenas\.(.*)\.cputemp\.temperatures\.(.*)'
              match_type: "regex"
              name: "cpu_temperature"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "cpu${2}"

            - match: 'truenas\.(.*)\.cpu\.core_throttling\.(.*)'
              match_type: "regex"
              name: "cpu_throttling"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "${2}"

            - match: 'truenas\.(.*)\.cpu\.cpufreq\.(.*)'
              match_type: "regex"
              name: "cpu_frequency"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "${2}"

            - match: 'truenas\.(.*)\.cpu\.(.*)_cpuidle\.(.*)'
              match_type: "regex"
              name: "cpu_idlestate"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "${2}"
                state: "${3}"

            - match: 'truenas\.(.*)\.cpu\.(.*)\.(.*)'
              match_type: "regex"
              name: "cpu_usage"
              labels:
                job: "truenas"
                instance: "${1}"
                cpu: "${2}"
                kind: "${3}"

            ################################################
            # process mapping
            ################################################

            - match: 'truenas\.(.*)\.system\.forks\.started'
              match_type: "regex"
              name: "processes_forks"
              labels:
                job: "truenas"
                instance: "${1}"

            - match: 'truenas\.(.*)\.system\.processes\.(.*)'
              match_type: "regex"
              name: "processes"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            - match: 'truenas\.(.*)\.system\.active_processes\.(.*)'
              match_type: "regex"
              name: "processes"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            ################################################
            # uptime mapping
            ################################################

            - match: 'truenas\.(.*)\.system\.uptime\.uptime'
              match_type: "regex"
              name: "uptime"
              labels:
                job: "truenas"
                instance: "${1}"

            - match: 'truenas\.(.*)\.system\.clock_sync_state\.state'
              match_type: "regex"
              name: "clock_synced"
              labels:
                job: "truenas"
                instance: "${1}"

            - match: 'truenas\.(.*)\.system\.clock_status\.(.*)'
              match_type: "regex"
              name: "clock_status"
              labels:
                job: "truenas"
                instance: "${1}"
                state: "${2}"

            - match: 'truenas\.(.*)\.system\.clock_sync_offset\.offset'
              match_type: "regex"
              name: "clock_offset"
              labels:
                job: "truenas"
                instance: "${1}"

            ################################################
            # load mapping
            ################################################

            - match: 'truenas\.(.*)\.system\.load\.(.*)'
              match_type: "regex"
              name: "system_load"
              labels:
                job: "truenas"
                instance: "${1}"
                kind: "${2}"

            ################################################
            # nsfd mappings
            ################################################

            - match: 'truenas\.(.*)\.nfsd\.(.*)\.(.*)'
              match_type: "regex"
              name: "nfs_${2}"
              labels:
                job: "truenas"
                instance: "${1}"
                op: "${3}"

            ################################################
            # zfs mappings
            ################################################

            - match: 'truenas\.(.*)\.zfs\.(.*)\.(.*)'
              match_type: "regex"
              name: "zfs_${2}"
              labels:
                job: "truenas"
                instance: "${1}"
                op: "${3}"

            - match: 'truenas\.(.*)\.zfspool\.state_(.*)\.(.*)'
              match_type: "regex"
              name: "zfs_pool"
              labels:
                job: "truenas"
                instance: "${1}"
                pool: "${2}"
                state: "${3}"

            ################################################
            # network mappings
            ################################################

            - match: 'truenas\.(.*)\.net\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_io"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.net_speed\.(.*)\.speed'
              match_type: "regex"
              name: "interface_speed"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"

            - match: 'truenas\.(.*)\.net_duplex\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_duplex"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                state: "${3}"

            - match: 'truenas\.(.*)\.net_operstate\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_operationstate"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                state: "${3}"

            - match: 'truenas\.(.*)\.net_carrier\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_carrierstate"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                state: "${3}"

            - match: 'truenas\.(.*)\.net_mtu\.(.*)\.mtu'
              match_type: "regex"
              name: "interface_mtu"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"

            - match: 'truenas\.(.*)\.net_packets\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_packets"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.net_errors\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_errors"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.net_drops\.(.*)\.(.*)'
              match_type: "regex"
              name: "interface_drops"
              labels:
                job: "truenas"
                instance: "${1}"
                interface: "${2}"
                op: "${3}"

            - match: 'truenas\.(.*)\.system\.net\.(.*)'
              match_type: "regex"
              name: "system_net_io"
              labels:
                job: "truenas"
                instance: "${1}"
                op: "${2}"
    serviceMonitor:
      app:
        serviceName: graphite-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    persistence:
      config:
        type: configMap
        name: graphite-exporter-configmap
        advancedMounts:
          graphite-exporter:
            app:
              - path: /config
                readOnly: true
