---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: smarthome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:

    image:
      repository: ghcr.io/koush/scrypted
      tag: 18-jammy-full-v0.41.0

    service:
      main:
        ports:
          http:
            port: 11080
          rebroadcast:
            port: 34135

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: scrypted.home
            paths:
              - path: /

    persistence:
      config:
        enabled: true
        mountPath: /server/volume
        existingClaim: scrypted-config-v1
      cache:
        enabled: true
        mountPath: /.cache
        type: emptyDir
      cache-npm:
        enabled: true
        mountPath: /.npm
        type: emptyDir
      recs:
        enabled: true
        mountPath: /recs
        existingClaim: nfs-scrypted-pvc

    resources:
      requests:
        cpu: 136m
        memory: 512Mi
      limits:
        memory: 1024Mi
