---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: element-jitsi-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://element-hq.github.io/jitsi-helm/
  timeout: 3m
