---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backube-charts.yaml
  - bitnami-charts.yaml
  - blakeshome-charts.yaml
  - charliehaley-charts.yaml
  - coredns-charts.yaml
  - deliveryhero-charts.yaml
  - drone-charts.yaml
  - grafana-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kasten-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - node-feature-discovery-charts.yaml
  - piraeus-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
  - appscode-charts.yaml
  - authentik-charts.yaml
  - bootc-charts.yaml
  - democratic-csi-charts.yaml
  - emqx-charts.yaml
  - falco-security-charts.yaml
  - gitea-charts.yaml
  - influxdata-charts.yaml
  - jmmaloney4-charts.yaml
  - kremers-charts.yaml
  - kubernetes-sigs-nfd-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - mglants-charts.yaml
  - mailu-charts.yaml
  - minecraft-server-charts.yaml
  - nextcloud-charts.yaml
  - vernemq-charts.yaml
  - vmware-tanzu-charts.yaml
  - timescale-charts.yaml
  - bjw-s-charts.yaml
  - loeken-at-home-charts.yaml
  - itzg-charts.yaml
  - angelnu-charts.yaml
  - cilium-charts.yaml
  - postfinance-charts.yaml
  - kubernetes-metrics-server-charts.yaml
  - kubernetes-sigs-external-dns-charts.yaml
  - cloudnative-pg-charts.yaml
  - external-secrets-charts.yaml
  - botkube-charts.yaml
  - crunchydata-charts.yaml
  - k8tz-charts.yaml
  - actions-runner-controller-charts.yaml
  - spegel-charts.yaml
  - ananace-charts.yaml
