---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mailu-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://mailu.github.io/helm-charts/
  timeout: 3m
