---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts
      chart: democratic-csi
      version: 0.13.4
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: org.democratic-csi.nfs
    node:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
    # add note here about volume expansion requirements
    storageClasses:
      - name: freenas-nfs-csi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs

        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: freenas-nfs-csi
        annotations:
          k10.kasten.io/is-snapshot-class: 'true'
          snapshot.storage.kubernetes.io/is-default-class: 'true'
        labels:
          velero.io/csi-volumesnapshot-class: 'true'
        parameters:
          detachedSnapshots: 'false'
        secrets:
          snapshotter-secret:

    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 172.16.30.200
          port: 80
          username: root
          allowInsecure: true
        zfs:
          cli:
            sudoEnabled: true
          datasetParentName: ssd/k8s/nfs
          detachedSnapshotsDatasetParentName: ssd/k8s/snap
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: '0777'
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 172.16.30.200
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: [172.16.30.0/24]
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ''
          shareMapallGroup: ''
  valuesFrom:
    - kind: Secret
      name: democratic-csi-values
      valuesKey: values.yaml
      optional: false
