---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: homeassistant-iot
  namespace: smarthome
spec:
  config: '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "eth0.10", "mode": "bridge", "ipam": { "type": "static", "addresses": [ { "address": "172.16.10.5/24"
    } ] } }'
