---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: home-assistant
  namespace: smarthome
spec:
  postgresVersion: 15
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        repo1-path: /home-assistant/repo1
        repo1-s3-uri-style: path
        repo1-storage-verify-tls: n
      repo:
        name: repo1
        s3:
          bucket: crunchy-postgres
          endpoint: 172.16.30.200
          port: 9000
          region: us-east-1
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: on
  instances:
    - name: postgres
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: home-assistant
      databases:
        - home-assistant
      options: SUPERUSER
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: '14'
        repo1-retention-full-type: time
        repo1-path: /home-assistant/repo1
        repo1-s3-uri-style: path
        repo1-storage-verify-tls: n
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: 0 1 * * 0
            differential: 0 1 * * 1-6
          s3:
            bucket: crunchy-postgres
            endpoint: 172.16.30.200
            port: 9000
            verify-tls: n
            region: us-east-1
