---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://infracloudio.github.io/charts
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.12.1
      pullPolicy: Always
    serviceMonitor:
      enabled: false                           # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)
    config:
      settings:
        clustername: k8s
        kubectl:
          # Set true to enable kubectl commands execution
          enabled: true
          # List of allowed commands
          commands:
            # kubectl method which are allowed with BotKube command
            verbs: [api-resources, api-versions, cluster-info, describe, diff, explain, get, logs, top, auth]
            # resources on which kubectl methods are allowed with BotKube commands
            resources: [deployments, pods, namespaces, daemonsets, statefulsets, storageclasses, nodes]
          # set Namespace to execute botkube kubectl commands by default
          defaultNamespace: default
          # Set true to enable commands execution from configured channel only
          restrictAccess: true
        # Set true to enable config watcher
        configwatcher: true
        # Set false to disable upgrade notification
        upgradeNotifier: true
      resources:
        - name: v1/pods
          namespaces:
            include:
              - all
            ignore:
              - kube-system
          events:
            - create
            - delete
        - name: v1/services
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: networking.k8s.io/v1/ingresses
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/secrets
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        # - name: v1/configmaps
        #   namespaces:
        #     include:
        #       - all
        #     ignore:
        #       - rook-ceph
        #   events:
        #     - delete
        #     - error
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        # - name: batch/v1/jobs
        #   namespaces:
        #     include:
        #       - all
        #     ignore:
        #       - rook-ceph
        #       - kube-system
        #   events:
        #     - create
        #     - update
        #     - delete
        #     - error
        #   updateSetting:
        #     includeDiff: true
        #     fields:
        #       - spec.template.spec.containers[*].image
        #       - status.conditions[*].type
        - name: rbac.authorization.k8s.io/v1/roles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
  valuesFrom:
    - kind: Secret
      name: botkube-communications-secret
      valuesKey: values.yaml
      optional: false
