---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: multus-cni
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 30m
  values:
    image:
      registry: docker.io
      repository: bitnami/multus-cni
      tag: 3.9.3
    hostCNIBinDir: /opt/cni/bin
    hostCNINetDir: /etc/cni/net.d
    CNIVersion: 0.3.1
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        cpu: 60m
        memory: 128Mi
