---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marzban-next-data-v1
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi
