---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vmware-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vmware-exporter-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vmware-exporter
