---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vmware-exporter
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://kremers.github.io
      chart: vmware-exporter
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: kremers-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: pryorda/vmware_exporter
      tag: v0.18.4
      pullPolicy: IfNotPresent
    replicaCount: 1
    readinessProbe: {}

    livenessProbe: {}
    vsphere:
      host: vsphere.ur30.ru
      ignoressl: true
      collectors:
        hosts: true
        datastores: true
        vms: true
        vmguests: false
        snapshots: false

    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9272'
      prometheus.io/path: /metrics
    service:
      enabled: true
      type: ClusterIP
      port: 9272
      targetport: 9272
  valuesFrom:
    - targetPath: vsphere.password
      kind: Secret
      name: vmware-exporter-secret
      valuesKey: PASSWORD
    - targetPath: vsphere.user
      kind: Secret
      name: vmware-exporter-secret
      valuesKey: USERNAME
