---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ipmi-exporter-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          modules:
            default:
              collectors:
                - ipmi
              user: "{{ .USERNAME }}"
              pass: "{{ .password }}"
              driver: "LAN_2_0"
              privilege: "user"
              timeout: 10000
  dataFrom:
    - extract:
        key: ipmi-exporter
