# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ocis
  namespace: flux-system
spec:
  targetNamespace: apps
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/subterra/apps/apps/ocis/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: cluster-apps-democratic-csi
    - name: cluster-apps-volsync
    - name: cluster-apps-external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: ocis-data
      VOLSYNC_CAPACITY: 15Gi
