---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-main
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 65005
      exportPodCIDR: false
      serviceSelector:
        matchExpressions:
          - {key: thisFakeSelector, operator: NotIn, values: [will-match-and-announce-all-services]}
      neighbors:
        - peerAddress: 192.168.48.1/32
          peerASN: 65000
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: 192.168.40.0/21
