---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: m@gearage.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      ## An empty 'selector' means that this solver matches all domains
      - selector: {}
        dns01:
          cloudflare:
            email: m@gearage.ru
            apiTokenSecretRef:
              name: cloudflare-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gearage-crt
  namespace: cert-manager
spec:
  secretName: gearage-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - gearage.ru
    - '*.gearage.ru'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ur30ru-crt
  namespace: cert-manager
spec:
  secretName: ur30ru-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ur30.ru
    - '*.ur30.ru'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glants-crt
  namespace: cert-manager
spec:
  secretName: glants-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - glants.xyz
    - '*.glants.xyz'
