---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: berries-core
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: berries-kubeconfig
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: berries-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/sh/berries/core
  prune: true
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: sync-settings-berries
        # substituteFrom:
        #   - kind: Secret
        #     name: cluster-secrets-berries
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: not-used
          namespace: not-used
        spec:
          interval: 30m
          timeout: 5m
          install:
            createNamespace: true
            crds: CreateReplace
            remediation:
              retries: 5
          upgrade:
            crds: CreateReplace
            remediation:
              retries: 5
      target:
        kind: HelmRelease
        group: helm.toolkit.fluxcd.io
        labelSelector: helmdefault.flux.home.arpa/disabled notin (true)
