---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters-sh
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: sidero-apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/sh
  prune: true
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-sidero
      - kind: ConfigMap
        name: cluster-settings-sidero
