---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stunner-tls
spec:
  secretName: stunner-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: turn.glants.xyz
