---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stunner-tls
  namespace: matrix
spec:
  secretName: stunner-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: turn.glants.xyz
  dnsNames:
    - turn.glants.xyz
