---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haste-server
  namespace: apps
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: haste-server
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/haste-server
      pullPolicy: IfNotPresent
      tag: latest
    env:
      TZ: Europe/Moscow
      STORAGE_FILEPATH: /config
      STORAGE_TYPE: file
    service:
      main:
        ports:
          http:
            port: 7777
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: haste.gearage.ru
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gearage-crt-secret
            hosts:
              - haste.gearage.ru
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: haste-server-config-v1
