---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-external-secret
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-external-secret
    creationPolicy: Owner
  data:
    - secretKey: cloudflare
      remoteRef:
        key: cloudflare
        property: cert-manager
