---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unifi
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/subterra/apps/networking/unifi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  components:
    - ../../../../components/kopiur/backup
  targetNamespace: networking
  postBuild:
    substitute:
      APP: unifi
      KOPIUR_CLAIM: unifi-config-v2
      KOPIUR_MOVER_UID: "999"
      KOPIUR_MOVER_GID: "999"
      KOPIUR_MOVER_FSGID: "1000"
      KOPIUR_MOVER_RUN_AS_NON_ROOT: "true"
