---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-secret
  namespace: matrix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: synapse-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: synapse
