---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
  namespace: matrix
spec:
  interval: 15m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.9.12
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/element-hq/synapse
      tag: 'v1.116.0'
      pullPolicy: IfNotPresent
    serverName: 'glants.xyz'
    publicServerName: 'matrix.glants.xyz'
    signingkey:
      job:
        enabled: true
    config:
      trustedKeyServers:
        - server_name: matrix.org
          verify_keys:
            "ed25519:auto": "Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw"
    extraConfig:
      email:
        smtp_host: smtp-relay.default.svc.cluster.local
        smtp_port: 587
        notif_from: "Your Friendly %(app)s homeserver <noreply@${SECRET_DOMAIN}>"
      presence:
        enabled: true
      enable_3pid_lookup: false

    synapse:
      strategy:
        type: Recreate
      podSecurityContext:
        fsGroup: 666
        runAsGroup: 666
        runAsUser: 666

      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 666
      resources:
        limits:
          cpu: 5
          memory: 5Gi
        requests:
          cpu: 1
          memory: 2Gi

    workers:
      default:
        replicaCount: 1
        podSecurityContext:
          fsGroup: 666
          runAsGroup: 666
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 666

        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
      generic_worker:
        enabled: false
        generic: true
        replicaCount: 2
        listeners: [client]
        csPaths:
          ## Sync requests
          # - "/_matrix/client/(r0|v3)/sync$"
          # - "/_matrix/client/(api/v1|r0|v3)/events$"
          # - "/_matrix/client/(api/v1|r0|v3)/initialSync$"
          # - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync$"

          ## Client API requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/createRoom$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/publicRooms$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/joined_members$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/context/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/members$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state$"
          - "/_matrix/client/v1/rooms/.*/hierarchy$"
          - "/_matrix/client/unstable/org.matrix.msc2716/rooms/.*/batch_send$"
          - "/_matrix/client/unstable/im.nheko.summary/rooms/.*/summary$"
          - "/_matrix/client/(r0|v3|unstable)/account/3pid$"
          - "/_matrix/client/(r0|v3|unstable)/account/whoami$"
          - "/_matrix/client/(r0|v3|unstable)/devices$"
          - "/_matrix/client/versions$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/event/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/joined_rooms$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/search$"

          ## Encryption requests
          - "/_matrix/client/(r0|v3|unstable)/keys/query$"
          - "/_matrix/client/(r0|v3|unstable)/keys/changes$"
          - "/_matrix/client/(r0|v3|unstable)/keys/claim$"
          - "/_matrix/client/(r0|v3|unstable)/room_keys/"

          ## Registration/login requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/login$"
          - "/_matrix/client/(r0|v3|unstable)/register$"
          - "/_matrix/client/v1/register/m.login.registration_token/validity$"

          ## Event sending requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/redact"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/send"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/join/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/profile/"

          ## User directory search requests
          - "/_matrix/client/(r0|v3|unstable)/user_directory/search"

          ## Worker event streams
          ## See https://matrix-org.github.io/synapse/latest/workers.html#stream-writers
          ##

          ## The typing event stream
          # - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/typing"

          ## The to_device event stream
          # - "/_matrix/client/(r0|v3|unstable)/sendToDevice/"

          ## The account_data event stream
          # - "/_matrix/client/(r0|v3|unstable)/.*/tags"
          # - "/_matrix/client/(r0|v3|unstable)/.*/account_data"

          ## The receipts event stream
          # - "/_matrix/client/(r0|v3|unstable)/rooms/.*/receipt"
          # - "/_matrix/client/(r0|v3|unstable)/rooms/.*/read_markers"

          ## The presence event stream
          - "/_matrix/client/(api/v1|r0|v3|unstable)/presence/"
      synchrotron:
        enabled: true
        generic: true
        listeners: [client]
        csPaths:
          - "/_matrix/client/(v2_alpha|r0|v3)/sync$"
          - "/_matrix/client/(api/v1|v2_alpha|r0|v3)/events$"
          - "/_matrix/client/(api/v1|r0|v3)/initialSync$"
          - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync$"
      federation_sender:
        enabled: true
        replicaCount: 2
      media_repository:
        enabled: true
        strategy:
          type: Recreate
      pusher:
        enabled: true
      frontend_proxy:
        enabled: false

    wellknown:
      enabled: true
      image:
        repository: ghcr.io/rtsp/docker-lighttpd
        tag: 1.4.76
        pullPolicy: Always
      podSecurityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 100
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100

      resources:
        limits:
          cpu: 5m
          memory: 15Mi
        requests:
          cpu: 5m
          memory: 15Mi

    postgresql:
      enabled: false
    externalPostgresql:
      existingSecret: synapse-pgsql-pguser-synapse
    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: synapse-secret
      architecture: standalone
      master:
        kind: Deployment
        persistence:
          enabled: false
        service:
          port: 6379
    persistence:
      enabled: true
      existingClaim: synapse-data-v1

    volumePermissions:
      enabled: true
    service:
      type: ClusterIP
      port: 8008
      targetPort: http

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru

      tls:
        - secretName: synapse-tls
          hosts:
            - glants.xyz
            - matrix.glants.xyz

      className: external-nginx
