---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data-v2
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 30Gi
