---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data-v1
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 30Gi
