---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-secret
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FRIGATE_MQTT_PASSWORD: '{{ .emqx_MQTT_PASSWORD }}'
        FRIGATE_RTSP_PASSWORD: '{{ .frigate_RTSP_PASSWORD }}'
  dataFrom:
    - extract:
        key: frigate
      rewrite:
        - regexp:
            source: (.*)
            target: frigate_$1
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: (.*)
            target: emqx_$1
