---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 8.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.12.1
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
        hosts:
          - host: frigate.home
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 5000
          rtsp:
            enabled: true
            port: 8554
            protocol: TCP
            targetPort: 8554
    securityContext:
      privileged: false
    persistence:
      data:
        enabled: true
        existingClaim: frigate-data-v1
        mountPath: /data
      media:
        enabled: true
        existingClaim: nfs-frigate-pvc
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 512Mi
        mountPath: /tmp/cache
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 1000Mi
        cpu: 750m
      limits:
        memory: 2000Mi
    env:
      TZ: Europe/Moscow
    configmap:
      config:
        enabled: true
  valuesFrom:
    - targetPath: configmap.config.data
      kind: Secret
      name: emqx-secret
      valuesKey: config.yml
