---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-v1
  namespace: smarthome
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
