---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp-dachia
  namespace: www
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: wordpress
      version: 15.2.9
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/wordpress
      tag: 5.9.3-debian-10-r12
      pullPolicy: IfNotPresent

    wordpressBlogName: User's Blog!
    wordpressTablePrefix: wp_
    wordpressScheme: https
    wordpressConfigureCache: true
    wordpressAutoUpdateLevel: minor
    wordpressExtraConfigContent: |
      @ini_set( 'upload_max_filesize' , '512M' );
      @ini_set( 'post_max_size', '512M');
      @ini_set( 'memory_limit', '1024M' );
    smtpHost: ''
    smtpPort: ''
    smtpUser: ''
    smtpPassword: ''
    smtpProtocol: ''
    extraVolumes:
      - name: php-args
        configMap:
          name: wp-dachia-php-args
          defaultMode: 0755
    extraVolumeMounts:
      - name: php-args
        mountPath: /opt/bitnami/php/etc/conf.d/
        readOnly: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostname: dachia.ur30.ru
      tls: true

    persistence:
      enabled: true
      existingClaim: wp-dachia-wp-v1

    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: bitnami_wordpress
        username: bn_wordpress
      primary:
        persistence:
          enabled: true
          existingClaim: wp-dachia-mariadb-v1
    memcached:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: wp-dachia-helm-values
      valuesKey: values.yaml
      optional: false
