---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-dachia-wp-v1
  namespace: www
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-dachia-mariadb-v1
  namespace: www
  labels:
    kasten.io/backup-volume: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
