---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - blackbox-exporter
  # - graphite-exporter
  - snmp-exporter
  # - ipmi-exporter
  - mikrotik-exporter
  - mqtt-exporter
