---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: default-arm64
spec:
  qualifiers:
    hardware:
      - compute:
          processors:
            - manufacturer: Broadcom
              productName: BCM2711 (ARM Cortex-A72)
