---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: master-sh
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
            vip:
              ip: ${CP_SH_IP}
  selector:
    matchLabels:
      master-node: 'true'
      region: sh
