---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: worker-sh
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
            vlans:
              - vlanId: 10
                mtu: 1500
                dhcp: true
                dhcpOptions:
                  routeMetric: 4096
                  ipv6: false
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/local-path-provisioner
          type: bind
          source: /var/local-path-provisioner
          options:
            - bind
            - rshared
            - rw
    - op: add
      path: /machine/files
      value:
        - op: create
          content: |
            [metrics]
              address = "0.0.0.0:11234"
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
    - op: add
      path: /machine/sysctls
      value:
        fs.inotify.max_user_watches: '1048576'
        fs.inotify.max_user_instances: '8192'
        vm.max_map_count: '524288'
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
        feature-gates: GracefulNodeShutdown=true
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets:
          - 172.16.30.0/24
    - op: add
      path: /cluster/aescbcEncryptionSecret
      value: ${aescbcEncryptionSecret_SH}
    - op: replace
      path: /cluster/discovery/registries/service/disabled
      value: true
    - op: remove
      path: /cluster/discovery/registries/kubernetes/disabled
      value: true
  selector:
    matchLabels:
      worker-node: 'true'
      region: sh
