---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: worker-sh
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
            vlans:
              - vlanId: 10
                dhcp: true
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/local-path-provisioner
          type: bind
          source: /var/local-path-provisioner
          options:
            - bind
            - rshared
            - rw
    - op: add
      path: /machine/files
      value:
        - op: create
          content: |
            [metrics]
              address = "0.0.0.0:11234"
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
        feature-gates: GracefulNodeShutdown=true
  selector:
    matchLabels:
      worker-node: 'true'
      region: sh
