---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./alertmanager/ks.yaml
  - ./botkube/ks.yaml
  - ./exporters/graphite-exporter/ks.yaml
  - ./exporters/ipmi-exporter/ks.yaml
  - ./exporters/mqtt-exporter/ks.yaml
  - ./exporters/smartctl-exporter/ks.yaml
  - ./exporters/snmp-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./nut/ks.yaml
  - ./vector/ks.yaml
