---
apiVersion: v1
kind: Secret
metadata:
  name: mailu-helm-values
  namespace: apps
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:a28U3tn7/49qWtMc75iJYyHhmF1QG3FN0dxg2uq3HBI8iaU5dgYdyAy5n9tMbjJUG+iScmwBFf1IxEnQWXqZ8uhJNlmIuhaZZEmc8bHlo/Xj5/iwI/E/Jc5e0YjT2lndJ0vaEuiZ8Ki2ZkonRONyszupH2M41Hvnz8+Zwkb0t8p1PD5N8VeEjvqYk9Q3WVderLr78XNruoz5wlmRcLhTVjwuOJmwmShlSqmmHv+2tfPQgZWF/Uhze9tlDGo6kH+7AjO+MpHFV18ov1xXltN9DfuVyBuMmLuFkkI03TxJxk8dFL6DZvGdyxs1xIVOo2H/XREe95On86npORyHc3BMJ5ktJg0WUi+jew6l8hhbvZyHREf6bAL1kbRU09/wrjFve2QAg7Y/IQ==,iv:Xk9NAG46iifGuqLMBTxf2WGFZftdCtw8aFXmQoVU7Ko=,tag:QEJjmogEVBmtPHn+ADHGmQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-07-11T01:26:37Z'
  mac: ENC[AES256_GCM,data:7BLmzSL6mS8J5qXFIJTJFPlSD5a+7O+MPnvfkuBx5OT7J6n+AJ9uRS9ZRULExFy+8OtQ54svpJIQvuwOC3h4MdZsLs+l8g/8T/CmMKT+JWAiwt13WhqLOfvc7Jcdv5vHj/yWJ2/oRgmCJY3csjUnIxvwOj2CtjOsfhqcGacfrFk=,iv:pikDXHJFyndOeQK4Zhn3NG1Y7D7XTV+aDP49Rgdt0XA=,tag:tONnJqEd31Tmt29rofwtpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
