---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: 2.29.8
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
  values:
    image:
      repository: velero/velero
      tag: v1.11.0-rc.1
      pullPolicy: Always
    configuration:
      extraEnvVars:
        TZ: Europe/Moscow
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://172.16.30.200:9000
          publicUrl: http://172.16.30.200:9000
          insecureSkipTLSVerify: 'true'
      volumeSnapshotLocation:
        name: default
        provider: org.democratic-csi.nfs
      features: EnableCSI
    initContainers:
      - name: velero-plugin-for-aws
        image: ghcr.io/k8s-at-home/velero-plugin-for-aws:v1.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.5.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    schedules:
      daily-backup:
        schedule: 0 6 * * *
        template:
          ttl: 168h
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    backupsEnabled: true
    snapshotsEnabled: true
    upgradeCRDs: true
    cleanUpCRDs: true
    deployRestic: false
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    nodeSelector:
      beta.kubernetes.io/arch: amd64
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  valuesFrom:
    - kind: Secret
      name: velero-helm-values
      valuesKey: values.yaml
      optional: false
