---
apiVersion: v1
kind: Secret
metadata:
  name: velero-helm-values
  namespace: backup
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:T1/1CfnYkEJ1nDQo9nn8n2lwwMf/wSwpq+sTBbsZqcFnc/ALhQFjsA9Dm/3gRv3kULLwArgBN3TbcRPN3Ese+jL68iFRoQzy0I7bKtTbJVY9SmV4HHUWDXRblRBjbNd5Er8eioiRqcGgjf0SaL3tMpuKPSlKP4+YUNJWkpMnh5OLXve45049Itz3zVm5rSqriBmlk2V6yZSF50DaL6SAUVeyTeMIPudGdp+pta8j4E890FfPVX+CPmAytEsbuZoricfTVw9YZ6c=,iv:4ORLbtlP/YAUzZPl/XGkk4DvT7EcuYU0DkTCvRpdKBQ=,tag:sEeyp5P397ePLmcVuG0mmQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1s3vxakzjchpekyzum36gsyxtwurt8vj4skvffgc68hv6vkl6e3lslkjfk0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjZ3Q0JINDF5MkZvUzJE
        VTdMNEJMK0RJQzlFTXl4M0t1U0llWUVkZUFzCjZ3OU1lRWJUWHgxbHVoQjB0N0Np
        VkdrRGZtbFdaQ1JzNVoydE9pdzhkbncKLS0tIE1tcVhjWDJXVXJQVXlZWVd1allQ
        YlFsOHVZTEs3b2NwZ2Z3M3d2ejA3d0kKIbvkAOFoYBYwnLxLSgsY7ANIN7+S4ftr
        F1YqcOSORzfiTr+0g8iy2OPm0o3a1zWTegm1AkIXOXEuhivzsqdxfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-06-11T23:00:07Z'
  mac: ENC[AES256_GCM,data:b88nl1ZyS0ASpgiXszkkCq4MZTZ2Jbr5NQWMfcIJ2OxE6AtZZOwA2aPejv9NG40YesQl0yLySoEJcv5aIDbAw6bNhnlCDlvCEZ9irQYsczkXBdHGfGByxd7hmJGv+ac2eqIDesZDO3mFv5AQGNWTtx6wOGst0KSRiT8tVXHUti8=,iv:C/SDQib4CT5w7KHmwjYmlTH+7vtkyGXyoAFHLMiESSs=,tag:zSB+kdYnscMoBtX004HCdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
