---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: networking
  labels:
    # Avoid variable substitution of shell variables bellow
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/helm-charts
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  # See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/values.yaml
  values:
    image:
      repository: ghcr.io/b-tuma/pod-gateway-udp
      tag: v1.11.0
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        pullPolicy: Always
        tag: v3.10.0
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
    addons:
      vpn:
        enabled: true
        type: gluetun
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        gluetun:
          image:
            repository: qmcgaw/gluetun
            tag: v3.39.0
            pullPolicy: Always
        env:
          - name: VPN_SERVICE_PROVIDER
            value: custom
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: off
          - name: DOT
            value: off
        envFrom:
          - secretRef:
              name: vpn-gateway-secret
        # livenessProbe:
        #   exec:
        #     command:
        #       - sh
        #       - -c
        #       - if [ $(wget -q -O- https://ipinfo.io/country) == 'SE' ]; then exit 0; else exit $?; fi
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
        #   failureThreshold: 3

        networkPolicy:
          enabled: false

    routed_namespaces:
      - vpn
      - media
    DNSPolicy: ClusterFirst
    settings:
      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: 115
      # -- Traffic to these IPs will be send through the K8S gateway
      VPN_LOCAL_CIDRS: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
      DNS_LOCAL_CIDRS: cluster.local
      VXLAN_PORT: "4789"
      IPTABLES_NFT: "yes"
      VXLAN_ID: "42"
      VXLAN_IP_NETWORK: "172.16.1"
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
      - hostname: qbittorrent
        IP: 10
        ports:
          - type: udp
            port: 57047
          - type: tcp
            port: 57047
