---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-exporter
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: mqtt-exporter
      labels:
        app.kubernetes.io/name: mqtt-exporter
    spec:
      containers:
        - name: mqtt-exporter
          image: kpetrem/mqtt-exporter:latest
          imagePullPolicy: Always
          env:
            - name: MQTT_ADDRESS
              value: emqx.smarthome.svc
            - name: MQTT_TOPIC
              value: zigbee2mqtt/#
            - name: PROMETHEUS_PREFIX
              value: sensor_
            - name: TOPIC_LABEL
              value: sensor
            - name: ZIGBEE2MQTT_AVAILABILITY
              value: 'True'
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-exporter
                  key: mqtt_username
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-exporter
                  key: mqtt_password
          ports:
            - name: prometheus
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mqtt-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt-exporter
  ports:
    - name: prometheus
      port: 9000
      protocol: TCP
      targetPort: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-exporter
  endpoints:
    - port: prometheus
      metricRelabelings:
        - source_labels: [sensor]
          regex: zigbee2mqtt_(.*)
          replacement: $1
          target_label: sensor
---
...
