---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: backup
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: backube-charts
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: zimbres/volsync
    rclone:
      repository: zimbres/volsync
    restic:
      repository: zimbres/volsync
    rsync:
      repository: zimbres/volsync
    rsync-tls:
      repository: zimbres/volsync
    syncthing:
      repository: zimbres/volsync
    manageCRDs: true
    metrics:
      disableAuth: true
