---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name nextcloud-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Nextcloud
        ADMIN_USERNAME: '{{ .ADMIN_USERNAME }}'
        ADMIN_PASSWORD: '{{ .ADMIN_PASSWORD }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        SMTP_HOST: '{{ .SMTP_HOST }}'
        SMTP_USERNAME: '{{ .SMTP_USERNAME }}'
        SMTP_PASSWORD: '{{ .SMTP_PASSWORD }}'
        METRICS_TOKEN: '{{ .METRICS_TOKEN }}'
        INSTANCE_ID: '{{ .INSTANCE_ID }}'
        PASSWORD_SALT: '{{ .PASSWORD_SALT }}'
        ENCRYPTION_SECRET: '{{ .ENCRYPTION_SECRET }}'
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: smtp
