---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: [ReadWriteMany]
  storageClassName: nextcloud-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: /mnt/Storinator/NextCloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
