---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.10.6
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: influxdb
      tag: 1.8.10
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      existingClaim: influxdb-data-v1
    resources:
      requests:
        memory: 1000Mi
        cpu: 100m
      limits:
        memory: 4000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    config:
      opentsdb:
        enabled: true
      graphite:
        enabled: true
        database: graphitedb
        retention-policy: ''
        bind-address: :2003
        protocol: tcp
        consistency-lvel: one
        templates:
          - '*.app env.service.resource.measurement'
          - servers.* .host.resource.measurement.field*
