---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kea
  namespace: networking
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kea
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: kea-config
      labels:
        app: kea
    spec:
      volumes:
        - name: kea-config
          configMap:
            name: kea-config
            items:
              - key: config
                path: kea-dhcp4.conf
        - name: kea-leases
          persistentVolumeClaim:
            claimName: kea-pvc
      containers:
        - name: kea
          image: winglim/kea-dhcp4:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/kea
              name: kea-leases
            - mountPath: /etc/kea
              name: kea-config
          ports:
            - name: dhcp
              containerPort: 67
              protocol: UDP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 50Mi
