---
apiVersion: v1
kind: Service
metadata:
  name: kea
  namespace: networking
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.40.2
  selector:
    app: kea
  ports:
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: dhcp
