---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mqtt-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_USERNAME: '{{ .emqx_MQTT_USERNAME }}'
        MQTT_PASSWORD: '{{ .emqx_MQTT_PASSWORD }}'
  dataFrom:
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: (.*)
            target: emqx_$1
