---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-v2
  namespace: monitoring
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
