---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  maxHistory: 2
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.3.4
    env:
      TZ: Europe/Moscow
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 172.16.32.200
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.org/websocket-services: home-assistant
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: ha.glants.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ha-glants-crt
            hosts:
              - ha.glants.xyz

    metrics:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      enabled: false
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
        labels: {}
        ## See https://www.home-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        # bearerTokenSecret:
        #   name: ""
        #   key: ""
      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: false
        labels: {}
        # -- Configure additionial rules for the chart under this key.
        # @default -- See prometheusrules.yaml
        rules: []
        # - alert: HomeAssistantAbsent
        #   annotations:
        #     description: Home Assistant has disappeared from Prometheus service discovery.
        #     summary: Home Assistant is down.
        #   expr: |
        #     absent(up{job=~".*home-assistant.*"} == 1)
        #   for: 5m
        #   labels:
        #     severity: critical
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config-v1
    podAnnotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.10.1
        workingDir: /config
        args:
          - --user-data-dir
          - /config/.vscode
          - --auth
          - none
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.214.0/24, 10.13.12.0/24
          hosts:
            - host: ha-vscode.home
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    postgresql:
      enabled: true
      image:
        repository: arm64v8/postgres
        tag: 14.3
      volumePermissions:
        enabled: true
        image:
          repository: arm64v8/alpine
          tag: '3.17'
      securityContext:
        fsGroup: 999
        runAsUser: 999
      livenessProbe:
        initialDelaySeconds: 60
      readinessProbe:
        initialDelaySeconds: 60
      auth:
        username: homeassistant
        database: homeassistant
      persistence:
        primary:
          enabled: true
  valuesFrom:
    - kind: Secret
      name: homeassistant-helm-values
      valuesKey: values.yaml
      optional: false
