---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-v1
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
