---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: berries
  namespace: flux-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: berries-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: berries
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: berries
  namespace: flux-system
spec:
  controlPlaneEndpoint:
    host: 172.16.30.10
    port: 6443