---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: berries-cp
  namespace: flux-system
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: master-sh
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: berries-cp
  namespace: flux-system
spec:
  version: ${K8s_SH_VERSION}
  replicas: 2
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  infrastructureTemplate:
    kind: MetalMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: berries-cp
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_SH_VERSION}
