---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.19
    controller:
      replicas: 2
      strategy: RollingUpdate
      rollingUpdate:
        surge: 50%
        unavailable: 1
    env:
      TZ: Europe/Moscow
    service:
      main:
        ports:
          http:
            port: 4000
      dns-udp:
        enabled: true
        type: ClusterIP
        ClusterIP: 10.233.51.1
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
    metrics:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
        labels: {}
      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: false
        labels: {}
        # -- Configure additionial rules for the chart under this key.
        # @default -- See prometheusrules.yaml
        rules: []
    podAnnotations:
      configmap.reloader.stakater.com/reload: blocky-config
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - blocky
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi
    config: |-
      bootstrapDns: tcp+udp:1.1.1.1
      upstream:
        default:
        - tcp-tls:1.1.1.1
        - tcp-tls:dns3.digitalcourage.de:853
        - tcp-tls:dnsse.alekberg.net:443
        - https://cloudflare-dns.com/dns-query
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://easylist-downloads.adblockplus.org/advblock.txt
          kids:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/billimek/k8s-gitops/master/default/blocky/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:10.0.7.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
