---
kind: Service
apiVersion: v1
metadata:
  name: asterisk-service
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/hostname: asterisk.home
spec:
  type: ExternalName
  externalName: 172.16.30.250
