---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sidero-apps
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: sidero-core
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/ur30/sidero/apps
  prune: true
  validation: client
  postBuild:
    substitute: {}
    substituteFrom:
      # - kind: Secret
      #   name: cluster-secrets-sidero
      - kind: ConfigMap
        name: cluster-settings-sidero
  decryption:
    provider: sops
    secretRef:
      name: sops-age
