---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sidero-crds
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/ur30/sidero/crds
  prune: false
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-sidero
      - kind: ConfigMap
        name: cluster-settings-sidero
  decryption:
    provider: sops
    secretRef:
      name: sops-age
