---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sidero-gitops
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/ur30/sidero/gitops
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
