---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-secret
  namespace: smarthome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: |
          mqtt:
            host: emqx
            topic_prefix: frigate
            user: '{{ .emqx_MQTT_USERNAME }}'
            password: '{{ .emqx_MQTT_PASSWORD }}'

          database:
            path: /data/frigate.db
          birdseye:
            enabled: true
            # restream: true
            mode: continuous

          objects:
            track:
              - person
            filters:
              person:
                min_area: 2500
                max_area: 100000
                threshold: 0.75

          record:
            enabled: true
            retain:
              days: 3
              mode: motion
            alerts:
              retain:
                days: 30
                mode: motion
            detections:
              retain:
                days: 30
                mode: motion

          review:
            alerts:
              labels:
                - person
            detections:
              labels:
                - person

          snapshots:
            enabled: true
            timestamp: false
            bounding_box: true
            crop: false
            retain:
              default: 7

          go2rtc:
            streams:
              frigate_intercom_hq: rtsp://admin:{{ .frigate_RTSP_PASSWORD }}@172.16.11.10:554/ISAPI/Streaming/Channels/101
              frigate_intercom_lq: rtsp://admin:{{ .frigate_RTSP_PASSWORD }}@172.16.11.10:554/ISAPI/Streaming/Channels/102
          cameras:
            hallway:
              ffmpeg:
                inputs:
                  - path: rtsp://localhost:8554/frigate_intercom_lq
                    roles:
                      - detect
                  - path: rtsp://localhost:8554/frigate_intercom_hq
                    roles:
                      - record
              detect:
                height: 576
                width: 704
                fps: 5
              objects:
                filters:
                  person:
                    min_area: 1500
                    max_area: 100000
                    threshold: 0.75
                    min_score: 0.60

  dataFrom:
    - extract:
        key: frigate
      rewrite:
        - regexp:
            source: (.*)
            target: frigate_$1
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: (.*)
            target: emqx_$1
