---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate-pv
  namespace: smarthome
spec:
  storageClassName: frigate
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.30.200
    path: /mnt/bulky/frigate
  mountOptions:
    - noatime
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-frigate-pvc
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: frigate
  resources:
    requests:
      storage: 1Mi
