---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: smarthome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: koenkk/zigbee2mqtt
      # -- image tag
      tag: 1.27.0
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [image docs](https://www.zigbee2mqtt.io/information/configuration.html#override-via-environment-variables) for more details.
    # @default -- See below
    env:
      # -- Set the data folder for Zigbee2MQTT.
      ZIGBEE2MQTT_DATA: /data

    # -- Configures service settings for the chart. Normally this does not need to be modified.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            primary: true
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.214.0/24, 10.13.12.0/24
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: zigbee2mqtt.home
            paths:
              - path: /
                pathType: Prefix


    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: zigbee2mqtt-settings

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt-data-v1

    # -- Configure a hostPathMount to mount a USB device in the container.
    # @default -- See values.yaml
    # usb:
    #   enabled: true
    #   type: hostPath
    #   mountPath: /dev/ttyUSB0
    #   hostPath: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
    # -- Affinity constraint rules to place the Pod on a specific node.
    # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}

    # -- zigbee2mqtt configuration settings.
    # This will be copied into the container's persistent storage at first run only.
    # Further configuration should be done in the application itself!
    # See [project documentation](https://www.zigbee2mqtt.io/information/configuration.html) for more information.
    # @default -- See values.yaml
    config:
      # These will be applied ONLY on first run
      # Home Assistant integration (MQTT discovery)
      homeassistant: true
      # allow new devices to join
      # WARNING: Disable this after all devices have been paired! (default: false)
      # Note: this will be controllable in the UI
      permit_join: false
      availability:
        active:
          # Time after which an active device will be marked as offline in
          # minutes (default = 10 minutes)
          timeout: 10
        passive:
          # Time after which a passive device will be marked as offline in
          # minutes (default = 1500 minutes aka 25 hours)
          timeout: 1500
      # MQTT settings
      mqtt:
        # MQTT base topic for zigbee2mqtt MQTT messages
        base_topic: zigbee2mqtt
        # MQTT server URL
        server: mqtt://emqx
        # MQTT server authentication, uncomment if required:
        user: mqtt
        client_id: zigbee2mqtt
        # Alternatively, credentials may be put into a separate file, managed through a secret:
        # password: '!secret password'

        # Optional: Include device information to mqtt messages (default: false)
        include_device_information: true

      # USB / Serial settings
      serial:
        # Location of your zigbee device
        port: tcp://172.16.10.20:20108
        # Optional: adapter type, not needed unless you are experiencing problems (options: zstack, deconz)
        # adapter: zstack

      advanced:
        transmit_power: 20
        pan_id: 6754 - console
        log_level: info

        # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
        # default: 11
        channel: 11

        # Optional: Baudrate for serial port (default: 115200 for Z-Stack, 38400 for Deconz)
        # baudrate: 38400

        # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
        # rtscts: true

        # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
        # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
        last_seen: ISO_8601

        homeassistant_discovery_topic": homeassistant
        homeassistant_legacy_entity_attributes: true
        homeassistant_legacy_triggers: false
        homeassistant_status_topic: homeassistant/status

        # Optional: Enables report feature (see information -> report for more details) (default: false)
        # report: true

        # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
        # elapsed: true

      # Both of these need to be enabled for the webui
      frontend:
        port: 8080
      experimental:
        new_api: true
      device_options:
        occupancy_timeout: 600
      devices:
        '0x00158d0006a15678':
          occupancy_timeout: 600
        '0x00158d0006a15726':
          occupancy_timeout: 600
        '0x00158d0003f0f1e8':
          occupancy_timeout: 600
  valuesFrom:
    - kind: Secret
      name: zigbee2mqtt-helm-values
      valuesKey: values.yaml
      optional: false
