---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: marzban-restic
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: marzban-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/marzban'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: marzban
  namespace: apps
spec:
  sourcePVC: marzban-data-v1
  trigger:
    schedule: 0 */12 * * *
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: marzban-restic-secret
    retain:
      hourly: 24
      daily: 7
      weekly: 5
    volumeSnapshotClassName: freenas-iscsi-csi
    storageClassName: freenas-iscsi-csi
    cacheStorageClassName: freenas-iscsi-csi
