---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: 'true'

        pod:
          annotations:
            setGateway: 'true'
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 105
              - 10000

        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.10.3
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: 'true'
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              TZ: Europe/Moscow
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 9248M
              limits:
                memory: 9248M

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.17
        ports:
          http:
            port: 8096

    ingress:
      app:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        className: external-nginx
        hosts:
          - host: &hostName jellyfin.ur30.ru
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: jellyfin-tls
            hosts:
              - *hostName

    persistence:
      config:
        existingClaim: jellyfin-config-v1
        advancedMounts:
          jellyfin:
            app:
              - path: /config
      nfs-nas-media:
        existingClaim: nfs-public-pvc
        advancedMounts:
          jellyfin:
            app:
              - path: /media
      transcode:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /transcode
