---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gammu-kz-secret
  namespace: apps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gammu
