---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-webhook-url
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        address: '{{ .flux_DISCORD_HTTP_WEBHOOK }}'
  dataFrom:
    - extract:
        key: flux
      rewrite:
        - regexp:
            source: (.*)
            target: flux_$1
