---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/external-secrets.io_clustersecretstores.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/external-secrets.io_externalsecrets.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/external-secrets.io_secretstores.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/generators.external-secrets.io_acraccesstokens.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/generators.external-secrets.io_ecrauthorizationtokens.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/generators.external-secrets.io_fakes.yaml
  # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/generators.external-secrets.io_gcraccesstokens.yaml
   # renovate: registryUrl=https://charts.external-secrets.io chart=external-secrets
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.3/config/crds/bases/generators.external-secrets.io_passwords.yaml
commonAnnotations:
  meta.helm.sh/release-name: external-secrets-operator
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
